import { NormalEntry } from "../prompt-define.mjs";
import { EmotionTag } from "../tag-defines/emotion.mjs";

const emotionPresetPiece = {
  smile: [`blush`, `smile`],
  smilePartedLips: [`blush`, `smile`, `parted lips`],
  smileOpenMouth: [`blush`, `smile`, `:d`, `open mouth`],
  smileClosedMouth: [`blush`, `smile`, `closed mouth`],
  lightSmileOpenMouth: [`blush`, `light smile`, `open mouth`],
  lightSmileClosedMouth: [`blush`, `light smile`, `closed mouth`],
  smileHalfClosedEyes: [`blush`, `smile`, `half-closed eyes`],
  expressionless: [`blush`, `expressionless`],
  surprised: [`blush`, `surprised`, `:o`, `open mouth`, `!`],
  confused: [`blush`, `nose blush`, `confused`, `?`],
  embarrassed: [`blush`, `nose blush`, `embarrassed`],
  nervous: [`blush`, `nose blush`, `nervous`],
  flustered: [`blush`, `nose blush`, `flustered`],
  seductiveSmile: [`blush`, `seductive smile`],
  naughtyFace: [`blush`, `naughty face`, `smile`, `half-closed eyes`],
  scowl: [`blush`, `nose blush`, `scowl`],
  angry: [`blush`, `angry`],
  oneEyeClosed: [
    `blush`,
    `smile`,
    `one eye closed`,
    [{ entries: [`;\\)`, `closed mouth`] }, { entries: [`;o`, `open mouth`] }],
  ],
  grin: [`blush`, `smile`, `grin`],
  doyagao: [`blush`, `smug`, `doyagao`, `v-shaped eyebrows`, `puff of air`],
} as const satisfies { [k in string]: NormalEntry<EmotionTag>[] };

export const emotionPreset = {
  cute: [
    [
      { entries: emotionPresetPiece.smileClosedMouth, probability: 2 },
      { entries: emotionPresetPiece.smileOpenMouth, probability: 2 },
      { entries: emotionPresetPiece.smilePartedLips },
      { entries: emotionPresetPiece.smileHalfClosedEyes },
      { entries: emotionPresetPiece.expressionless },
      { entries: emotionPresetPiece.surprised },
      { entries: emotionPresetPiece.confused },
      { entries: emotionPresetPiece.embarrassed },
      { entries: emotionPresetPiece.nervous },
      { entries: emotionPresetPiece.flustered },
      { entries: emotionPresetPiece.seductiveSmile, probability: 3 },
      { entries: emotionPresetPiece.naughtyFace },
      { entries: emotionPresetPiece.oneEyeClosed, probability: 2 },
    ],
  ],
  serious: [
    [
      { entries: emotionPresetPiece.lightSmileOpenMouth, probability: 1 },
      { entries: emotionPresetPiece.lightSmileClosedMouth, probability: 3 },
      { entries: emotionPresetPiece.smilePartedLips },
      { entries: emotionPresetPiece.smileHalfClosedEyes },
      { entries: emotionPresetPiece.expressionless },
      { entries: emotionPresetPiece.surprised },
      { entries: emotionPresetPiece.embarrassed },
      { entries: emotionPresetPiece.nervous },
      { entries: emotionPresetPiece.flustered },
      { entries: emotionPresetPiece.seductiveSmile, probability: 3 },
      { entries: emotionPresetPiece.naughtyFace },
      { entries: emotionPresetPiece.scowl },
    ],
  ],
  uptight: [
    [
      { entries: emotionPresetPiece.lightSmileOpenMouth, probability: 1 },
      { entries: emotionPresetPiece.lightSmileClosedMouth, probability: 2 },
      { entries: emotionPresetPiece.smilePartedLips },
      { entries: emotionPresetPiece.smileHalfClosedEyes },
      { entries: emotionPresetPiece.expressionless },
      { entries: emotionPresetPiece.surprised },
      { entries: emotionPresetPiece.embarrassed, probability: 3 },
      { entries: emotionPresetPiece.nervous },
      { entries: emotionPresetPiece.flustered },
      { entries: emotionPresetPiece.seductiveSmile, probability: 3 },
      { entries: emotionPresetPiece.naughtyFace },
      { entries: emotionPresetPiece.scowl, probability: 2 },
      { entries: emotionPresetPiece.angry },
    ],
  ],
  deadpanned: [
    [
      { entries: emotionPresetPiece.lightSmileClosedMouth, probability: 2 },
      { entries: emotionPresetPiece.smilePartedLips },
      { entries: emotionPresetPiece.smileOpenMouth },
      { entries: emotionPresetPiece.smileHalfClosedEyes, probability: 2 },
      { entries: emotionPresetPiece.expressionless, probability: 3 },
      { entries: emotionPresetPiece.embarrassed },
      { entries: emotionPresetPiece.nervous },
      { entries: emotionPresetPiece.flustered },
      { entries: emotionPresetPiece.seductiveSmile, probability: 3 },
      { entries: emotionPresetPiece.naughtyFace },
    ],
  ],
  mesugaki: [
    [
      { entries: emotionPresetPiece.smileOpenMouth, probability: 2 },
      { entries: emotionPresetPiece.smilePartedLips },
      { entries: emotionPresetPiece.grin, probability: 3 },
      { entries: emotionPresetPiece.smileOpenMouth },
      { entries: emotionPresetPiece.smileHalfClosedEyes },
      { entries: emotionPresetPiece.expressionless },
      { entries: emotionPresetPiece.embarrassed },
      { entries: emotionPresetPiece.nervous },
      { entries: emotionPresetPiece.flustered },
      { entries: emotionPresetPiece.seductiveSmile, probability: 3 },
      { entries: emotionPresetPiece.naughtyFace },
    ],
  ],
} as const satisfies { [k in string]: NormalEntry<EmotionTag>[] };
