import { PoseDefine } from "../../resolver.mjs";

export const fromBelowPawPose = {
  entries: [
    `from below`,
    `cowboy shot`,
    `paw pose`,
    `hands up`,
    `looking down`,
    `looking at viewer`,
  ],
  visibility: {
    frontHead: true,
    sideHead: true,
    backHead: false,
    frontBreast: true,
    sideBreast: true,
    backBreast: false,
    frontMidriff: true,
    sideMidriff: true,
    backMidriff: false,
    frontHipAndThigh: true,
    sideHipAndThigh: true,
    backHipAndThigh: false,
    foot: false,
    wristAndHand: true,
    aroundBody: true,
  },
  specialVisibility: {
    armpits: false,
    hangingBreasts: false,
    tautClothes: true,
    cleavage: false,
    sideboob: false,
    backboob: false,
    underboobLevel: `from below`,
    zettaiRyouiki: true,
    insideOfThighs: true,
    upskirt: true,
  },
} as const satisfies PoseDefine;
