const allBackgroundTags = [
  `indoors`,
  `cafe`,
  `bed`,
  `lamp`,
  `window`,
  `classroom`,
  `office`,
  `night`,
  `outdoors`,
  `beach`,
  `ocean`,
  `city`,
  `rooftop`,
  `cityscape`,
  `confetti`,
  `blue sky`,
  `mountain`,
  `rock`,
  `forest`,
  `garden`,
  `simple background`,
  `white background`,
  `pink background`,
  `heart background`,
  `heart`,
  `spoken heart`,
  `cave interior`,
  `ceiling`,
  `sunset`,
  `orange sky`,
  `night sky`,
  `grass`,
  `floor`,
  `wooden floor`,
  `partially submerged`,
  `bed sheet`,
  `pillow`,
] as const satisfies readonly string[];
export type BackgroundTag = (typeof allBackgroundTags)[number];
