export const allCharacterName = [
  `shinonono houki`,
  `cecilia alcott`,
  `charlotte dunois`,
  `huang lingyin`,
  `laura bodewig`,
  `yamada maya \(infinite stratos\)`,
  `orimura chifuyu`,
  `kafuu chino`,
  `hoto cocoa`,
  `tedeza rize`,
  `ujimatsu chiya`,
  `kirima syaro`,
  `jouga maya`,
  `natsu megumi`,
  `yor briar`,
  `nishikigi chisato`,
  `inoue takina`,
  `shokuhou misaki`,
  `sento isuzu`,
  `latifa fleuranza`,
  `salama \(amaburi\)`,
  `koborii \(amaburi\)`,
  `muse \(amaburi\)`,
  `sylphy \(amaburi\)`,
  `suzukaze aoba`,
  `takimoto hifumi`,
  `sairenji haruna`,
  `lala satalin deviluke`,
  `nana asta deviluke`,
  `momo velia deviluke`,
  `konjiki no yami`,
  `kurosaki mea`,
  `kotegawa yui`,
  `yui kotegawa`,
  `tamaki iroha`,
  `nanami yachiyo`,
  `shiba miyuki`,
  `saegusa mayumi`,
  `chiba erika`,
  `shibata mizuki`,
  `kitayama shizuku`,
  `mitsui honoka`,
] as const satisfies readonly string[];
export type CharacterNameTag = (typeof allCharacterName)[number];
