import { HeadOutfitTags } from "./head-outfit.mjs";

const allExposureTags = [
  `collarbone`,
  `bare shoulders`,
  `bare arms`,
  `nipples`,
  `covered niples`,
  `midriff`,
  `navel`,
  `covered navel`,
  `shoulder blades`,
  `skin tight`,
  `skindentation`,
  `bare legs`,
  `cameltoe`,
  `pussy`,
  `ass`,
  `butt crack`,
  `barefoot`,
  `no shoes`,
  `partially unbuttoned`,
  `partially undressed`,
  `nsfw`,
  `shiny skin`,
] as const satisfies readonly string[];
type ExposureTag = (typeof allExposureTags)[number];

const allShirtColorTags = [
  `aqua shirt`,
  `black shirt`,
  `blue shirt`,
  `brown shirt`,
  `green shirt`,
  `grey shirt`,
  `orange shirt`,
  `pink shirt`,
  `purple shirt`,
  `red shirt`,
  `white shirt`,
  `yellow shirt`,
] as const satisfies string[];

const allSkirtColorTags = [
  `aqua skirt`,
  `black skirt`,
  `blue skirt`,
  `brown skirt`,
  `green skirt`,
  `grey skirt`,
  `orange skirt`,
  `pink skirt`,
  `purple skirt`,
  `red skirt`,
  `white skirt`,
  `yellow skirt`,
] as const satisfies string[];

const allPantiesColorTags = [
  `aqua panties`,
  `black panties`,
  `blue panties`,
  `brown panties`,
  `green panties`,
  `grey panties`,
  `orange panties`,
  `pink panties`,
  `purple panties`,
  `red panties`,
  `white panties`,
  `yellow panties`,
] as const satisfies string[];

const allBowtieColorTags = [
  `aqua bowtie`,
  `black bowtie`,
  `blue bowtie`,
  `brown bowtie`,
  `green bowtie`,
  `grey bowtie`,
  `orange bowtie`,
  `pink bowtie`,
  `purple bowtie`,
  `red bowtie`,
  `white bowtie`,
  `yellow bowtie`,
] as const satisfies string[];

const allBikiniColorTags = [
  `multicolored bikini`,
  `aqua bikini`,
  `black bikini`,
  `blue bikini`,
  `brown bikini`,
  `gold bikini`,
  `green bikini`,
  `grey bikini`,
  `orange bikini`,
  `pink bikini`,
  `purple bikini`,
  `red bikini`,
  `silver bikini`,
  `white bikini`,
  `yellow bikini`,
] as const satisfies string[];

const allOnePieceSwimsuitColorTags = [
  `aqua one-piece swimsuit`,
  `black one-piece swimsuit`,
  `blue one-piece swimsuit`,
  `brown one-piece swimsuit`,
  `gold one-piece swimsuit`,
  `green one-piece swimsuit`,
  `grey one-piece swimsuit`,
  `orange one-piece swimsuit`,
  `pink one-piece swimsuit`,
  `purple one-piece swimsuit`,
  `red one-piece swimsuit`,
  `silver one-piece swimsuit`,
  `white one-piece swimsuit`,
  `yellow one-piece swimsuit`,
] as const satisfies string[];

const allJacketColorTags = [
  `aqua jacket`,
  `black jacket`,
  `blue jacket`,
  `brown jacket`,
  `green jacket`,
  `grey jacket`,
  `orange jacket`,
  `pink jacket`,
  `purple jacket`,
  `red jacket`,
  `white jacket`,
  `yellow jacket`,
] as const satisfies string[];

const allDressColorTags = [
  `aqua dress`,
  `black dress`,
  `blue dress`,
  `brown dress`,
  `green dress`,
  `grey dress`,
  `orange dress`,
  `pink dress`,
  `purple dress`,
  `red dress`,
  `white dress`,
  `yellow dress`,
] as const satisfies string[];

const allOutfitTags = [
  `cleavage cutout`,
  `navel cutout`,
  `neck ribbon`,
  `underbust`,
  `bowtie`,
  ...allBowtieColorTags,
  `buttons`,
  `jewelry`,
  `bikini`,
  ...allBikiniColorTags,
  `frilled bikini`,
  `print bikini`,
  `o-ring bikini`,
  `micro bikini`,
  `school swimsuit`,
  ...allOnePieceSwimsuitColorTags,
  `o-ring top`,
  `o-ring bottom`,
  `school uniform`,
  `jacket`,
  ...allJacketColorTags,
  `sleeveless jacket`,
  `military jacket`,
  `dress`,
  ...allDressColorTags,
  `two-tone dress`,
  `black collar`,
  `red collar`,
  `long sleeves`,
  `white sleeves`,
  `black sleeves`,
  `wide sleeves`,
  `belt`,
  `black belt`,
  `white belt`,
  `red belt`,
  `pink belt`,
  `detached collar`,
  `detached sleeves`,
  `maid`,
  `maid headdress`,
  `maid bikini`,
  `frills`,
  `apron`,
  `frilled apron`,
  `maid apron`,
  `waist apron`,
  `shirt`,
  ...allShirtColorTags,
  `collared shirt`,
  `vest`,
  `green vest`,
  `yellow vest`,
  `blue vest`,
  `black vest`,
  `off shoulder`,
  `off-shoulder dress`,
  `off-shoulder sweater`,
  `sweater`,
  `red sweater`,
  `sweater dress`,
  `office lady`,
  `choker`,
  `strap`,
  `gloves`,
  `black gloves`,
  `fingerless gloves`,
  `infinite stratos academy school uniform`,
  `lycoris uniform`,
  `pleated dress`,
  `bikini skirt`,
  `skirt`,
  ...allSkirtColorTags,
  `miniskirt`,
  `plaid skirt`,
  `pencil skirt`,
  `high-low skirt`,
  `red trim`,
  `pantyhose`,
  `thighhighs`,
  `black thighhighs`,
  `socks`,
  `white socks`,
  `black socks`,
  `shoes`,
  `loafers`,
  `boots`,
  `underwear`,
  `underwear only`,
  `lingerie`,
  `bra`,
  `panties`,
  ...allPantiesColorTags,
  `crotch seam`,
  `lace panties`,
  `tokiwadai school uniform`,
  `sweater vest`,
  `brown sweater vest`,
  `yellow sweater vest`,
  `short sleeves`,
  `white gloves`,
  `elbow gloves`,
  `pleated skirt`,
  `frilled skirt`,
  `white thighhighs`,
  `sleeveless`,
  `sleeveless shirt`,
  `sleeveless dress`,
  `aiguillette`,
  `epaulettes`,
  `blazer`,
  `suit`,
  `business suit`,
  `pinstripe pattern`,
  `pumps`,
  `open clothes`,
  `open jacket`,
  `open shirt`,
  `pirate`,
  `pirate hat`,
  `ascot`,
  `gold trim`,
  `thigh boots`,
  `playboy bunny`,
  `rabbit ears`,
  `fake animal ears`,
  `latex leotard`,
  `wrist cuffs`,
  `leotard`,
  `red leotard`,
  `pink leotard`,
  `orange leotard`,
  `yellow leotard`,
  `green leotard`,
  `blue leotard`,
  `purple leotard`,
  `black leotard`,
  `white leotard`,
  `brown leotard`,
  `rabbit tail`,
  `magical girl`,
  `cloak`,
  `white cloak`,
  `hood`,
  `hood up`,
  `hooded cloak`,
  `bodystocking`,
  `black footwear`,
  `cross-laced footwear`,
  `panties under pantyhose`,
  `serafuku`,
  `sailor collar`,
  `blue sailor collar`,
  `neckerchief`,
  `red neckerchief`,
  `crop top`,
  `crop top overhang`,
  `cropped shirt`,
  `naked shirt`,
  `dress shirt`,
  `no bra`,
  `bottomless`,
  `camisole`,
  `red camisole`,
  `blue camisole`,
  `green camisole`,
  `yellow camisole`,
  `orange camisole`,
  `aqua camisole`,
  `white camisole`,
  `black camisole`,
  `pink camisole`,
  `purple camisole`,
  `shorts`,
  `denim shorts`,
  `gym uniform`,
  `gym shirt`,
  `buruma`,
  `sweat`, // TODO: Move.
  `necklace`,
  `wedding dress`,
  `nontraditional wedding dress`,
  `bride`,
  `veil`,
  `bridal veil`,
  `hair ornament`,
  `hair flower`,
  `bridal garter`,
  `bridal gauntlets`,
  `bridal lingerie`,
  `garter belt`,
  `garter straps`,
  `revealing clothes`,
  `clothing cutout`,
  `sainan high school uniform`,
  `thigh strap`,
  `first high school uniform`,
  `collared dress`,
  `pencil dress`,
  `necktie`,
  `black necktie`,
  `short necktie`,
  `cropped jacket`,
  `miko`,
  `nontraditional miko`,
  `hakama`,
  `hakama skirt`,
  `hip vent`,
  `cheerleader`,
] as const satisfies readonly string[];
type OutfitTag = (typeof allOutfitTags)[number];

export type OutfitAndExposureTag = HeadOutfitTags | ExposureTag | OutfitTag;

// export const allOutdoorFootwearTags = [
//   `shoes`,
//   `colored shoe soles`,
//   `aqua footwear`,
//   `black footwear`,
//   `blue footwear`,
//   `brown footwear`,
//   `green footwear`,
//   `grey footwear`,
//   `orange footwear`,
//   `pink footwear`,
//   `purple footwear`,
//   `red footwear`,
//   `white footwear`,
//   `yellow footwear`,
//   `flats`,
//   `high heels`,
//   `loafers`,
//   `mary janes`,
//   `oxfords`,
//   `pointy footwear`,
//   `rudder footwear`,
//   `slippers`,
//   `sneakers`,
//   `high tops`,
//   `toeless footwear`,
//   `uwabaki`,
//   `winged footwear`,
//   `footwear bow`,
//   `footwear ribbon`,
//   `shoe soles`,
// ] as const satisfies string[];
// type OutdoorFootwearTag = (typeof allOutdoorFootwearTags)[number];
