const allPoseTags = [
  `looking at viewer`,
  `looking back`,
  `looking up`,
  `portrait`,
  `upper body`,
  `cowboy shot`,
  `all fours`,
  `from behind`,
  `upskirt`,
  `lying`,
  `on back`,
  `on bed`,
  `legs up`,
  `spread legs`,
  `clothes lift`,
  `dress lift`,
  `skirt lift`,
  `leaning forward`,
] as const satisfies readonly string[];
export type PoseTag = (typeof allPoseTags)[number];
