export const allSeriesName = [
  `amagi brilliant park`,
  `assault lily`,
  `blend s`,
  `bocchi the rock!`,
  `boku no hero academia`,
  `fate/kaleid liner prisma illya`,
  `gochuumon wa usagi desu ka?`,
  `gridman universe`,
  `hige wo soru\. soshite joshikousei wo hirou\.`,
  `infinite stratos`,
  `isekai nonbiri nouka`,
  `isekai ojisan`,
  `kage no jitsuryokusha ni naritakute!`,
  `kaguya-sama wa kokurasetai ~tensai-tachi no renai zunousen~`,
  `kanojo mo kanojo`,
  `kono subarashii sekai ni shukufuku wo!`,
  `lycoris recoil`,
  `machikado mazoku`,
  `magia record: mahou shoujo madoka magica gaiden`,
  `mahou shoujo madoka magica`,
  `mahouka koukou no rettousei`,
  `majo no tabitabi`,
  `megami-ryou no ryoubo-kun`,
  `mushoku tensei`,
  `new game!`,
  `non non biyori`,
  `rakudai kishi no cavalry`,
  `re:zero kara hajimeru isekai seikatsu`,
  `rokudenashi majutsu koushi to akashic record`,
  `ryuuou no oshigoto!`,
  `saenai heroine no sodatekata`,
  `saijaku muhai no bahamut`,
  `seiken gakuin no maken tsukai`,
  `shy \(series\)`,
  `sono bisque doll wa koi wo suru`,
  `spy x family`,
  `ssss\.dynazenon`,
  `ssss\.gridman`,
  `sword art online`,
  `to love-ru`,
  `to love-ru darkness`,
  `toaru kagaku no railgun`,
  `working!!`,
  `dumbbell nan kilo moteru?`,
  `dungeon ni deai wo motomeru no wa machigatteiru darou ka`,
  `mahou shoujo ni akogarete`,
] as const satisfies readonly string[];

export type SeriesNameTag = (typeof allSeriesName)[number];
