import { getKeys } from "../libs/utility.mjs";
import { createWriteStream } from "node:fs";
import { CharacterFeatureTag } from "./character-feature.mjs";
import { OutfitAndExposureTag } from "./outfit-and-exposure.mjs";

export const visibilityKeys = [
  `frontHead`,
  `sideHead`,
  `backHead`,
  `frontBreast`,
  `sideBreast`,
  `backBreast`,
  `frontMidriff`,
  `sideMidriff`,
  `backMidriff`,
  `frontHipAndThigh`,
  `sideHipAndThigh`,
  `backHipAndThigh`,
  `foot`,
  `wristAndHand`,
  `aroundBody`,
] as const satisfies string[];
export type VisibilityKeys = (typeof visibilityKeys)[number];

export type Visibility = Readonly<{
  [k in VisibilityKeys]: boolean;
}>;

const all = {
  frontHead: true,
  sideHead: true,
  backHead: true,
  frontBreast: true,
  sideBreast: true,
  backBreast: true,
  frontMidriff: true,
  sideMidriff: true,
  backMidriff: true,
  frontHipAndThigh: true,
  sideHipAndThigh: true,
  backHipAndThigh: true,
  foot: true,
  wristAndHand: true,
  aroundBody: true,
} as const satisfies Visibility;

const invisible = {
  frontHead: false,
  sideHead: false,
  backHead: false,
  frontBreast: false,
  sideBreast: false,
  backBreast: false,
  frontMidriff: false,
  sideMidriff: false,
  backMidriff: false,
  frontHipAndThigh: false,
  sideHipAndThigh: false,
  backHipAndThigh: false,
  foot: false,
  wristAndHand: false,
  aroundBody: false,
} as const satisfies Visibility;

export const visibleType = {
  all,
  invisible,
  face: {
    ...invisible,
    frontHead: true,
  },
  hair: {
    ...invisible,
    frontHead: true,
    sideHead: true,
    backHead: true,
  },
  hat: {
    ...invisible,
    frontHead: true,
    sideHead: true,
    backHead: true,
  },
  glasses: {
    ...invisible,
    frontHead: true,
    sideHead: true,
    backHead: true,
  },
  breasts: {
    ...invisible,
    frontBreast: true,
    sideBreast: true,
    backBreast: true,
  },
  shortTail: {
    ...invisible,
    backHipAndThigh: true,
  },
  longTail: {
    ...invisible,
    backHipAndThigh: true,
    aroundBody: true,
  },
  thighs: {
    ...invisible,
    frontHipAndThigh: true,
    sideHipAndThigh: true,
    backHipAndThigh: true,
  },
  hips: {
    ...invisible,
    backHipAndThigh: true,
  },
  bowtie: {
    ...invisible,
    frontBreast: true,
  },
  shoulder: {
    ...invisible,
    frontBreast: true,
    sideBreast: true,
    backBreast: true,
  },
  cleavage: {
    ...invisible,
    frontBreast: true,
  },
  sideboob: {
    ...invisible,
    sideBreast: true,
  },
  backboob: {
    ...invisible,
    backBreast: true,
  },
  nipples: {
    ...invisible,
    frontBreast: true,
  },
  navel: {
    ...invisible,
    frontMidriff: true,
  },
  "shoulder blades": {
    ...invisible,
    backBreast: true,
  },
  dress: {
    ...invisible,
    frontBreast: true,
    sideBreast: true,
    backBreast: true,
    frontMidriff: true,
    sideMidriff: true,
    backMidriff: true,
    frontHipAndThigh: true,
    sideHipAndThigh: true,
    backHipAndThigh: true,
  },
  shirt: {
    ...invisible,
    frontBreast: true,
    sideBreast: true,
    backBreast: true,
    frontMidriff: true,
    sideMidriff: true,
    backMidriff: true,
  },
  "breasts skindentation": {
    ...invisible,
    frontBreast: true,
    sideBreast: true,
  },
  cameltoe: {
    ...invisible,
    frontHipAndThigh: true,
  },
  "zettai ryouiki": {
    ...invisible,
    frontHipAndThigh: true,
    backHipAndThigh: true,
  },
  foot: {
    ...invisible,
    foot: true,
  },
  underbust: {
    ...invisible,
    frontMidriff: true,
    sideMidriff: true,
    backMidriff: true,
  },
  bra: {
    ...invisible,
    frontBreast: true,
    sideBreast: true,
    backBreast: true,
  },
  panties: {
    ...invisible,
    frontHipAndThigh: true,
    sideHipAndThigh: true,
    backHipAndThigh: true,
  },
  collar: {
    ...invisible,
    frontBreast: true,
    sideBreast: true,
    backBreast: true,
  },
  skirt: {
    ...invisible,
    frontHipAndThigh: true,
    sideHipAndThigh: true,
    backHipAndThigh: true,
  },
  "high-waist skirt": {
    ...invisible,
    frontMidriff: true,
    sideMidriff: true,
    backMidriff: true,
    frontHipAndThigh: true,
    sideHipAndThigh: true,
    backHipAndThigh: true,
  },
  "wrist cuffs": {
    ...invisible,
    wristAndHand: true,
  },
  "elbow gloves": {
    ...invisible,
    frontBreast: true,
    sideBreast: true,
    backBreast: true,
    wristAndHand: true,
  },
  thighhighs: {
    ...invisible,
    frontHipAndThigh: true,
    sideHipAndThigh: true,
    backHipAndThigh: true,
    foot: true,
  },
  "clothing cutout": {
    ...invisible,
    frontHipAndThigh: true,
    sideHipAndThigh: true,
    backHipAndThigh: true,
    frontMidriff: true,
    sideMidriff: true,
    backMidriff: true,
  },
  "side hip": {
    ...invisible,
    sideHipAndThigh: true,
  },
  "center frills": {
    ...invisible,
    frontBreast: true,
    frontMidriff: true,
  },
  "side-tie bikini bottom": {
    ...invisible,
    sideHipAndThigh: true,
  },
  armlet: {
    ...invisible,
    frontBreast: true,
    sideBreast: true,
    backBreast: true,
  },
} as const satisfies { [k: string]: Visibility };

const allEyesColorVisibilities = {
  "aqua eyes": visibleType.face,
  "black eyes": visibleType.face,
  "blue eyes": visibleType.face,
  "brown eyes": visibleType.face,
  "green eyes": visibleType.face,
  "grey eyes": visibleType.face,
  "orange eyes": visibleType.face,
  "pink eyes": visibleType.face,
  "purple eyes": visibleType.face,
  "red eyes": visibleType.face,
  "white eyes": visibleType.face,
  "yellow eyes": visibleType.face,
} as const;

const allHairColorVisibilities = {
  "multicolored hair": visibleType.hair,
  "streaked hair": visibleType.hair,
  "aqua hair": visibleType.hair,
  "black hair": visibleType.hair,
  "blonde hair": visibleType.hair,
  "blue hair": visibleType.hair,
  "light blue hair": visibleType.hair,
  "dark blue hair": visibleType.hair,
  "brown hair": visibleType.hair,
  "light brown hair": visibleType.hair,
  "green hair": visibleType.hair,
  "dark green hair": visibleType.hair,
  "light green hair": visibleType.hair,
  "grey hair": visibleType.hair,
  "orange hair": visibleType.hair,
  "pink hair": visibleType.hair,
  "purple hair": visibleType.hair,
  "light purple hair": visibleType.hair,
  "red hair": visibleType.hair,
  "white hair": visibleType.hair,
} as const;

const allEyesVisibilities = {
  "sparkling eyes": visibleType.face,
  "star-shaped pupils": visibleType.face,
  "+ +": visibleType.face,
  "symbol-shaped pupils": visibleType.face,
  heterocromia: visibleType.face,
  tsurime: visibleType.face,
  tareme: visibleType.face,
  jitome: visibleType.face,
} as const;

const allEyebrowsVisibilities = {
  eyebrows: visibleType.face,
  "short eyebrows": visibleType.face,
  "thick eyebrows": visibleType.face,
  hikimayu: visibleType.face,
} as const;

const allEyelashesVisibilities = {
  eyelashes: visibleType.face,
  "long eyelashes": visibleType.face,
  "thick eyelashes": visibleType.face,
} as const;

const allHairLengthVisibilities = {
  "short hair": visibleType.hair,
  "medium hair": visibleType.hair,
  "long hair": visibleType.hair,
  "very long hair": visibleType.hair,
  "absurdly long hair": visibleType.hair,
} as const;

const allBreastSizeVisibilities = {
  "flat chest": visibleType.breasts,
  "small breasts": visibleType.breasts,
  "medium breasts": visibleType.breasts,
  "large breasts": visibleType.breasts,
  "huge breasts": visibleType.breasts,
} as const;

const allDistinguishableBodyFeatureVisibilities = {
  "aqua short tail": visibleType.shortTail,
  "black short tail": visibleType.shortTail,
  "blue short tail": visibleType.shortTail,
  "brown short tail": visibleType.shortTail,
  "green short tail": visibleType.shortTail,
  "grey short tail": visibleType.shortTail,
  "orange short tail": visibleType.shortTail,
  "pink short tail": visibleType.shortTail,
  "purple short tail": visibleType.shortTail,
  "red short tail": visibleType.shortTail,
  "white short tail": visibleType.shortTail,
  "yellow short tail": visibleType.shortTail,
  "aqua long tail": visibleType.longTail,
  "black long tail": visibleType.longTail,
  "blue long tail": visibleType.longTail,
  "brown long tail": visibleType.longTail,
  "green long tail": visibleType.longTail,
  "grey long tail": visibleType.longTail,
  "orange long tail": visibleType.longTail,
  "pink long tail": visibleType.longTail,
  "purple long tail": visibleType.longTail,
  "red long tail": visibleType.longTail,
  "white long tail": visibleType.longTail,
  "yellow long tail": visibleType.longTail,
} as const;

const allDistinguishableHeadOutfitVisibilities = {
  "aqua hair bow": visibleType.hair,
  "black hair bow": visibleType.hair,
  "blue hair bow": visibleType.hair,
  "brown hair bow": visibleType.hair,
  "green hair bow": visibleType.hair,
  "grey hair bow": visibleType.hair,
  "orange hair bow": visibleType.hair,
  "pink hair bow": visibleType.hair,
  "purple hair bow": visibleType.hair,
  "red hair bow": visibleType.hair,
  "white hair bow": visibleType.hair,
  "yellow hair bow": visibleType.hair,
  "aqua hair ribbon": visibleType.hair,
  "black hair ribbon": visibleType.hair,
  "blue hair ribbon": visibleType.hair,
  "brown hair ribbon": visibleType.hair,
  "green hair ribbon": visibleType.hair,
  "grey hair ribbon": visibleType.hair,
  "orange hair ribbon": visibleType.hair,
  "pink hair ribbon": visibleType.hair,
  "purple hair ribbon": visibleType.hair,
  "red hair ribbon": visibleType.hair,
  "white hair ribbon": visibleType.hair,
  "yellow hair ribbon": visibleType.hair,
  "jingle bell hair ornament": visibleType.hair,
} as const;

const allEyewearColorVisibilities = {
  "aqua-framed eyewear": visibleType.glasses,
  "black-framed eyewear": visibleType.glasses,
  "blue-framed eyewear": visibleType.glasses,
  "brown-framed eyewear": visibleType.glasses,
  "green-framed eyewear": visibleType.glasses,
  "grey-framed eyewear": visibleType.glasses,
  "orange-framed eyewear": visibleType.glasses,
  "pink-framed eyewear": visibleType.glasses,
  "purple-framed eyewear": visibleType.glasses,
  "red-framed eyewear": visibleType.glasses,
  "white-framed eyewear": visibleType.glasses,
  "yellow-framed eyewear": visibleType.glasses,
} as const;

const allTintedEyewearColorVisibilities = {
  "blue-tinted eyewear": visibleType.glasses,
  "green-tinted eyewear": visibleType.glasses,
  "orange-tinted eyewear": visibleType.glasses,
  "pink-tinted eyewear": visibleType.glasses,
  "purple-tinted eyewear": visibleType.glasses,
  "red-tinted eyewear": visibleType.glasses,
  "yellow-tinted eyewear": visibleType.glasses,
} as const;

const allHairBowColorVisibilities = {
  "red bow": visibleType.hair,
  "pink bow": visibleType.hair,
  "orange bow": visibleType.hair,
  "brown bow": visibleType.hair,
  "yellow bow": visibleType.hair,
  "green bow": visibleType.hair,
  "aqua bow": visibleType.hair,
  "blue bow": visibleType.hair,
  "purple bow": visibleType.hair,
  "black bow": visibleType.hair,
  "grey bow": visibleType.hair,
  "white bow": visibleType.hair,
} as const;

const allHairbandColorVisibilities = {
  "red hairband": visibleType.hair,
  "pink hairband": visibleType.hair,
  "orange hairband": visibleType.hair,
  "brown hairband": visibleType.hair,
  "yellow hairband": visibleType.hair,
  "green hairband": visibleType.hair,
  "aqua hairband": visibleType.hair,
  "blue hairband": visibleType.hair,
  "purple hairband": visibleType.hair,
  "black hairband": visibleType.hair,
  "grey hairband": visibleType.hair,
  "white hairband": visibleType.hair,
} as const;

const allDistinguishableExposureVisibilities = {
  "breasts skindentation": visibleType["breasts skindentation"],
  "thighs skindentation": visibleType.thighs,
  "front neck star tattoo": visibleType.bowtie,
} as const;

const allDistinguishableOutfitVisibilities = {
  "gold trim shirt": visibleType.shirt,
  "gold trim skirt": visibleType.skirt,
  "red trim shirt": visibleType.shirt,
  "red trim skirt": visibleType.skirt,
  "pinstripe pattern shirt": visibleType.shirt,
  "pinstripe pattern skirt": visibleType.skirt,
  "navel o-ring": visibleType.navel,
  "neck jingle bell": visibleType.bowtie,
  "aqua neck ribbon": visibleType.bowtie,
  "black neck ribbon": visibleType.bowtie,
  "blue neck ribbon": visibleType.bowtie,
  "brown neck ribbon": visibleType.bowtie,
  "green neck ribbon": visibleType.bowtie,
  "grey neck ribbon": visibleType.bowtie,
  "orange neck ribbon": visibleType.bowtie,
  "pink neck ribbon": visibleType.bowtie,
  "purple neck ribbon": visibleType.bowtie,
  "red neck ribbon": visibleType.bowtie,
  "white neck ribbon": visibleType.bowtie,
  "yellow neck ribbon": visibleType.bowtie,
} as const;

const allShirtColorVisibilities = {
  "aqua shirt": visibleType.shirt,
  "black shirt": visibleType.shirt,
  "blue shirt": visibleType.shirt,
  "brown shirt": visibleType.shirt,
  "green shirt": visibleType.shirt,
  "grey shirt": visibleType.shirt,
  "orange shirt": visibleType.shirt,
  "pink shirt": visibleType.shirt,
  "purple shirt": visibleType.shirt,
  "red shirt": visibleType.shirt,
  "white shirt": visibleType.shirt,
  "yellow shirt": visibleType.shirt,
} as const;

const allSkirtColorVisibilities = {
  "aqua skirt": visibleType.skirt,
  "black skirt": visibleType.skirt,
  "blue skirt": visibleType.skirt,
  "brown skirt": visibleType.skirt,
  "green skirt": visibleType.skirt,
  "grey skirt": visibleType.skirt,
  "orange skirt": visibleType.skirt,
  "pink skirt": visibleType.skirt,
  "purple skirt": visibleType.skirt,
  "red skirt": visibleType.skirt,
  "white skirt": visibleType.skirt,
  "yellow skirt": visibleType.skirt,
} as const;

const allPantiesColorVisibilities = {
  "aqua panties": visibleType.panties,
  "black panties": visibleType.panties,
  "blue panties": visibleType.panties,
  "brown panties": visibleType.panties,
  "green panties": visibleType.panties,
  "grey panties": visibleType.panties,
  "orange panties": visibleType.panties,
  "pink panties": visibleType.panties,
  "purple panties": visibleType.panties,
  "red panties": visibleType.panties,
  "white panties": visibleType.panties,
  "yellow panties": visibleType.panties,
} as const;

const allBowtieColorVisibilities = {
  "aqua bowtie": visibleType.bowtie,
  "black bowtie": visibleType.bowtie,
  "blue bowtie": visibleType.bowtie,
  "brown bowtie": visibleType.bowtie,
  "green bowtie": visibleType.bowtie,
  "grey bowtie": visibleType.bowtie,
  "orange bowtie": visibleType.bowtie,
  "pink bowtie": visibleType.bowtie,
  "purple bowtie": visibleType.bowtie,
  "red bowtie": visibleType.bowtie,
  "white bowtie": visibleType.bowtie,
  "yellow bowtie": visibleType.bowtie,
} as const;

const allBikiniColorVisibilities = {
  "multicolored bikini": visibleType.dress,
  "aqua bikini": visibleType.dress,
  "black bikini": visibleType.dress,
  "blue bikini": visibleType.dress,
  "brown bikini": visibleType.dress,
  "gold bikini": visibleType.dress,
  "green bikini": visibleType.dress,
  "grey bikini": visibleType.dress,
  "orange bikini": visibleType.dress,
  "pink bikini": visibleType.dress,
  "purple bikini": visibleType.dress,
  "red bikini": visibleType.dress,
  "silver bikini": visibleType.dress,
  "white bikini": visibleType.dress,
  "yellow bikini": visibleType.dress,
} as const;

const allOnePieceSwimsuitColorVisibilities = {
  "aqua one-piece swimsuit": visibleType.dress,
  "black one-piece swimsuit": visibleType.dress,
  "blue one-piece swimsuit": visibleType.dress,
  "brown one-piece swimsuit": visibleType.dress,
  "gold one-piece swimsuit": visibleType.dress,
  "green one-piece swimsuit": visibleType.dress,
  "grey one-piece swimsuit": visibleType.dress,
  "orange one-piece swimsuit": visibleType.dress,
  "pink one-piece swimsuit": visibleType.dress,
  "purple one-piece swimsuit": visibleType.dress,
  "red one-piece swimsuit": visibleType.dress,
  "silver one-piece swimsuit": visibleType.dress,
  "white one-piece swimsuit": visibleType.dress,
  "yellow one-piece swimsuit": visibleType.dress,
} as const;

const allJacketColorVisibilities = {
  "aqua jacket": visibleType.shirt,
  "black jacket": visibleType.shirt,
  "blue jacket": visibleType.shirt,
  "brown jacket": visibleType.shirt,
  "green jacket": visibleType.shirt,
  "grey jacket": visibleType.shirt,
  "orange jacket": visibleType.shirt,
  "pink jacket": visibleType.shirt,
  "purple jacket": visibleType.shirt,
  "red jacket": visibleType.shirt,
  "white jacket": visibleType.shirt,
  "yellow jacket": visibleType.shirt,
} as const;

const allDressColorVisibilities = {
  "aqua dress": visibleType.dress,
  "black dress": visibleType.dress,
  "blue dress": visibleType.dress,
  "brown dress": visibleType.dress,
  "green dress": visibleType.dress,
  "grey dress": visibleType.dress,
  "orange dress": visibleType.dress,
  "pink dress": visibleType.dress,
  "purple dress": visibleType.dress,
  "red dress": visibleType.dress,
  "white dress": visibleType.dress,
  "yellow dress": visibleType.dress,
} as const;

const allSweaterColorVisibilities = {
  "aqua sweater": visibleType.shirt,
  "beige sweater": visibleType.shirt,
  "black sweater": visibleType.shirt,
  "brown sweater": visibleType.shirt,
  "blue sweater": visibleType.shirt,
  "green sweater": visibleType.shirt,
  "grey sweater": visibleType.shirt,
  "orange sweater": visibleType.shirt,
  "purple sweater": visibleType.shirt,
  "red sweater": visibleType.shirt,
  "yellow sweater": visibleType.shirt,
  "white sweater": visibleType.shirt,
} as const;

const allSweaterVestColorVisibilities = {
  "aqua sweater vest": visibleType.shirt,
  "black sweater vest": visibleType.shirt,
  "blue sweater vest": visibleType.shirt,
  "brown sweater vest": visibleType.shirt,
  "green sweater vest": visibleType.shirt,
  "grey sweater vest": visibleType.shirt,
  "orange sweater vest": visibleType.shirt,
  "pink sweater vest": visibleType.shirt,
  "purple sweater vest": visibleType.shirt,
  "red sweater vest": visibleType.shirt,
  "white sweater vest": visibleType.shirt,
  "yellow sweater vest": visibleType.shirt,
} as const;

const allGlovesColorVisibilities = {
  "multicolored gloves": visibleType["wrist cuffs"],
  "aqua gloves": visibleType["wrist cuffs"],
  "black gloves": visibleType["wrist cuffs"],
  "blue gloves": visibleType["wrist cuffs"],
  "brown gloves": visibleType["wrist cuffs"],
  "green gloves": visibleType["wrist cuffs"],
  "grey gloves": visibleType["wrist cuffs"],
  "orange gloves": visibleType["wrist cuffs"],
  "pink gloves": visibleType["wrist cuffs"],
  "purple gloves": visibleType["wrist cuffs"],
  "red gloves": visibleType["wrist cuffs"],
  "white gloves": visibleType["wrist cuffs"],
  "yellow gloves": visibleType["wrist cuffs"],
} as const;

const allThighhighsColorVisibilities = {
  "black thighhighs": visibleType.thighhighs,
  "blue thighhighs": visibleType.thighhighs,
  "brown thighhighs": visibleType.thighhighs,
  "green thighhighs": visibleType.thighhighs,
  "grey thighhighs": visibleType.thighhighs,
  "orange thighhighs": visibleType.thighhighs,
  "pink thighhighs": visibleType.thighhighs,
  "purple thighhighs": visibleType.thighhighs,
  "red thighhighs": visibleType.thighhighs,
  "white thighhighs": visibleType.thighhighs,
  "yellow thighhighs": visibleType.thighhighs,
} as const;

const allSocksColorVisibilities = {
  "black socks": visibleType.foot,
  "blue socks": visibleType.foot,
  "brown socks": visibleType.foot,
  "green socks": visibleType.foot,
  "grey socks": visibleType.foot,
  "orange socks": visibleType.foot,
  "pink socks": visibleType.foot,
  "purple socks": visibleType.foot,
  "red socks": visibleType.foot,
  "white socks": visibleType.foot,
  "yellow socks": visibleType.foot,
} as const;

const allCollarColorVisibilities = {
  "black collar": visibleType.collar,
  "blue collar": visibleType.collar,
  "brown collar": visibleType.collar,
  "grey collar": visibleType.collar,
  "orange collar": visibleType.collar,
  "pink collar": visibleType.collar,
  "purple collar": visibleType.collar,
  "red collar": visibleType.collar,
  "white collar": visibleType.collar,
} as const;

const allSleevesColorVisibilities = {
  "aqua sleeves": visibleType.shoulder,
  "black sleeves": visibleType.shoulder,
  "blue sleeves": visibleType.shoulder,
  "brown sleeves": visibleType.shoulder,
  "green sleeves": visibleType.shoulder,
  "grey sleeves": visibleType.shoulder,
  "orange sleeves": visibleType.shoulder,
  "pink sleeves": visibleType.shoulder,
  "purple sleeves": visibleType.shoulder,
  "red sleeves": visibleType.shoulder,
  "white sleeves": visibleType.shoulder,
  "yellow sleeves": visibleType.shoulder,
} as const;

const allBeltColorVisibilities = {
  "black belt": visibleType.skirt,
  "blue belt": visibleType.skirt,
  "brown belt": visibleType.skirt,
  "green belt": visibleType.skirt,
  "grey belt": visibleType.skirt,
  "orange belt": visibleType.skirt,
  "pink belt": visibleType.skirt,
  "purple belt": visibleType.skirt,
  "red belt": visibleType.skirt,
  "white belt": visibleType.skirt,
  "yellow belt": visibleType.skirt,
} as const;

const allVestColorVisibilities = {
  "aqua vest": visibleType.shirt,
  "black vest": visibleType.shirt,
  "blue vest": visibleType.shirt,
  "brown vest": visibleType.shirt,
  "green vest": visibleType.shirt,
  "grey vest": visibleType.shirt,
  "orange vest": visibleType.shirt,
  "pink vest": visibleType.shirt,
  "purple vest": visibleType.shirt,
  "red vest": visibleType.shirt,
  "white vest": visibleType.shirt,
  "yellow vest": visibleType.shirt,
} as const;

const allAscotColorVisibilities = {
  "aqua ascot": visibleType.bowtie,
  "black ascot": visibleType.bowtie,
  "blue ascot": visibleType.bowtie,
  "brown ascot": visibleType.bowtie,
  "green ascot": visibleType.bowtie,
  "grey ascot": visibleType.bowtie,
  "orange ascot": visibleType.bowtie,
  "pink ascot": visibleType.bowtie,
  "purple ascot": visibleType.bowtie,
  "red ascot": visibleType.bowtie,
  "white ascot": visibleType.bowtie,
  "yellow ascot": visibleType.bowtie,
} as const;

const allLeotardColorVisibilities = {
  "aqua leotard": visibleType.dress,
  "black leotard": visibleType.dress,
  "blue leotard": visibleType.dress,
  "brown leotard": visibleType.dress,
  "green leotard": visibleType.dress,
  "grey leotard": visibleType.dress,
  "orange leotard": visibleType.dress,
  "pink leotard": visibleType.dress,
  "purple leotard": visibleType.dress,
  "red leotard": visibleType.dress,
  "white leotard": visibleType.dress,
  "yellow leotard": visibleType.dress,
} as const;

const allNeckerchiefColorVisibilities = {
  "aqua neckerchief": visibleType.bowtie,
  "black neckerchief": visibleType.bowtie,
  "blue neckerchief": visibleType.bowtie,
  "brown neckerchief": visibleType.bowtie,
  "green neckerchief": visibleType.bowtie,
  "grey neckerchief": visibleType.bowtie,
  "orange neckerchief": visibleType.bowtie,
  "pink neckerchief": visibleType.bowtie,
  "purple neckerchief": visibleType.bowtie,
  "red neckerchief": visibleType.bowtie,
  "white neckerchief": visibleType.bowtie,
  "yellow neckerchief": visibleType.bowtie,
} as const;

const allSailorCollarColorVisibilities = {
  "aqua sailor collar": visibleType.collar,
  "black sailor collar": visibleType.collar,
  "blue sailor collar": visibleType.collar,
  "brown sailor collar": visibleType.collar,
  "green sailor collar": visibleType.collar,
  "grey sailor collar": visibleType.collar,
  "orange sailor collar": visibleType.collar,
  "pink sailor collar": visibleType.collar,
  "purple sailor collar": visibleType.collar,
  "red sailor collar": visibleType.collar,
  "white sailor collar": visibleType.collar,
  "yellow sailor collar": visibleType.collar,
} as const;

const allSerafukuColorVisibilities = {
  "aqua serafuku": visibleType.shirt,
  "black serafuku": visibleType.shirt,
  "blue serafuku": visibleType.shirt,
  "brown serafuku": visibleType.shirt,
  "green serafuku": visibleType.shirt,
  "grey serafuku": visibleType.shirt,
  "orange serafuku": visibleType.shirt,
  "pink serafuku": visibleType.shirt,
  "purple serafuku": visibleType.shirt,
  "red serafuku": visibleType.shirt,
  "white serafuku": visibleType.shirt,
  "yellow serafuku": visibleType.shirt,
} as const;

const allCamisoleColorVisibilities = {
  "aqua camisole": visibleType.shirt,
  "black camisole": visibleType.shirt,
  "blue camisole": visibleType.shirt,
  "brown camisole": visibleType.shirt,
  "green camisole": visibleType.shirt,
  "grey camisole": visibleType.shirt,
  "orange camisole": visibleType.shirt,
  "pink camisole": visibleType.shirt,
  "purple camisole": visibleType.shirt,
  "red camisole": visibleType.shirt,
  "white camisole": visibleType.shirt,
  "yellow camisole": visibleType.shirt,
} as const;

const allShortsColorVisibilities = {
  "multicolored shorts": visibleType.skirt,
  "aqua shorts": visibleType.skirt,
  "black shorts": visibleType.skirt,
  "blue shorts": visibleType.skirt,
  "brown shorts": visibleType.skirt,
  "green shorts": visibleType.skirt,
  "grey shorts": visibleType.skirt,
  "orange shorts": visibleType.skirt,
  "pink shorts": visibleType.skirt,
  "purple shorts": visibleType.skirt,
  "red shorts": visibleType.skirt,
  "white shorts": visibleType.skirt,
  "yellow shorts": visibleType.skirt,
} as const;

const allBurumaColorVisibilities = {
  "aqua buruma": visibleType.skirt,
  "black buruma": visibleType.skirt,
  "blue buruma": visibleType.skirt,
  "brown buruma": visibleType.skirt,
  "green buruma": visibleType.skirt,
  "grey buruma": visibleType.skirt,
  "orange buruma": visibleType.skirt,
  "pink buruma": visibleType.skirt,
  "purple buruma": visibleType.skirt,
  "red buruma": visibleType.skirt,
  "white buruma": visibleType.skirt,
  "yellow buruma": visibleType.skirt,
} as const;

const allNecktieColorVisibilities = {
  "aqua necktie": visibleType.bowtie,
  "black necktie": visibleType.bowtie,
  "blue necktie": visibleType.bowtie,
  "brown necktie": visibleType.bowtie,
  "green necktie": visibleType.bowtie,
  "grey necktie": visibleType.bowtie,
  "orange necktie": visibleType.bowtie,
  "pink necktie": visibleType.bowtie,
  "purple necktie": visibleType.bowtie,
  "red necktie": visibleType.bowtie,
  "white necktie": visibleType.bowtie,
  "yellow necktie": visibleType.bowtie,
} as const;

const allHatColorVisibilities = {
  "aqua hat": visibleType.hat,
  "black hat": visibleType.hat,
  "blue hat": visibleType.hat,
  "brown hat": visibleType.hat,
  "green hat": visibleType.hat,
  "grey hat": visibleType.hat,
  "orange hat": visibleType.hat,
  "pink hat": visibleType.hat,
  "purple hat": visibleType.hat,
  "red hat": visibleType.hat,
  "white hat": visibleType.hat,
  "yellow hat": visibleType.hat,
} as const;

// TODO: Separate color thigh boots from following defines.
const allFootwearColorVisibilities = {
  "aqua footwear": visibleType.foot,
  "black footwear": visibleType.foot,
  "blue footwear": visibleType.foot,
  "brown footwear": visibleType.foot,
  "green footwear": visibleType.foot,
  "grey footwear": visibleType.foot,
  "orange footwear": visibleType.foot,
  "pink footwear": visibleType.foot,
  "purple footwear": visibleType.foot,
  "red footwear": visibleType.foot,
  "white footwear": visibleType.foot,
  "yellow footwear": visibleType.foot,
} as const;

export const tagVisibilities = {
  // Head feature
  ...allEyesColorVisibilities,
  ...allHairColorVisibilities,
  ...allEyesVisibilities,
  ...allEyebrowsVisibilities,
  ...allEyelashesVisibilities,
  ...allHairLengthVisibilities,
  "gradient hair": visibleType.hair,
  "colored inner hair": visibleType.hair,
  "bob cut": visibleType.hair,
  "inverted bob": visibleType.hair,
  "pixie cut": visibleType.hair,
  undercut: visibleType.hair,
  "flipped hair": visibleType.hair,
  dreadlocks: visibleType.hair,
  "hime cut": visibleType.hair,
  "curly hair": visibleType.hair,
  "drill hair": visibleType.hair,
  "twin drills": visibleType.hair,
  "hair flaps": visibleType.hair,
  "messy hair": visibleType.hair,
  "pointy hair": visibleType.hair,
  ringlets: visibleType.hair,
  "straight hair": visibleType.hair,
  "wavy hair": visibleType.hair,
  "hair over shoulder": visibleType.hair,
  "short hair with long locks": visibleType.hair,
  "bow-shaped hair": visibleType.hair,
  braid: visibleType.hair,
  "braided bangs": visibleType.hair,
  "braided ponytail": visibleType.hair,
  "front braid": visibleType.hair,
  "side braid": visibleType.hair,
  "frentch braid": visibleType.hair,
  "crown braid": visibleType.hair,
  "single braid": visibleType.hair,
  "multiple braids": visibleType.hair,
  "twin braids": visibleType.hair,
  "low twin braids": visibleType.hair,
  "tri braids": visibleType.hair,
  "flower-shaped hair": visibleType.hair,
  "hair bun": visibleType.hair,
  "braided bun": visibleType.hair,
  "single hair bun": visibleType.hair,
  "double bun": visibleType.hair,
  "cone hair bun": visibleType.hair,
  "doughnut hair bun": visibleType.hair,
  "heart hair bun": visibleType.hair,
  "triple bun": visibleType.hair,
  "hair rings": visibleType.hair,
  "single hair ring": visibleType.hair,
  "half updo": visibleType.hair,
  "one side up": visibleType.hair,
  "two side up": visibleType.hair,
  "low-braided long hair": visibleType.hair,
  "low-tied long hair": visibleType.hair,
  mizura: visibleType.hair,
  "multi-tied-hair": visibleType.hair,
  ponytail: visibleType.hair,
  "folded ponytail": visibleType.hair,
  "high ponytail": visibleType.hair,
  "low ponytail": visibleType.hair,
  "short ponytail": visibleType.hair,
  "wide ponytail": visibleType.hair,
  "side ponytail": visibleType.hair,
  "split ponytail": visibleType.hair,
  topknot: visibleType.hair,
  twintails: visibleType.hair,
  "low twintails": visibleType.hair,
  "short twintails": visibleType.hair,
  "tri tails": visibleType.hair,
  "arched bangs": visibleType.face,
  "asymmetrical bangs": visibleType.face,
  "bangs pinned back": visibleType.face,
  "blunt bangs": visibleType.face,
  "center-flap bangs": visibleType.face,
  "crossed bangs": visibleType.face,
  "diagonal bangs": visibleType.face,
  "dyed bangs": visibleType.face,
  "hair over eyes": visibleType.face,
  "hair over one eye": visibleType.face,
  "long bangs": visibleType.face,
  "parted bangs": visibleType.face,
  "curtained bangs": visibleType.face,
  "hair between eyes": visibleType.face,
  "hair intakes": visibleType.face,
  "single hair intake": visibleType.face,
  "blunt ends": visibleType.hair,
  "swept bangs": visibleType.face,
  sidelocks: visibleType.hair,
  "asymmetrical sidelocks": visibleType.hair,
  "drill sidelocks": visibleType.hair,
  "low tied sidelocks": visibleType.hair,
  "single sidelock": visibleType.hair,
  ahoge: visibleType.hair,
  "heart ahoge": visibleType.hair,
  "huge ahoge": visibleType.hair,
  "antenna hair": visibleType.hair,
  "heart antenna hair": visibleType.hair,
  "hair pulled back": visibleType.hair,
  "hair slicked back": visibleType.hair,
  "alternate hairstyle": visibleType.hair,
  "hair down": visibleType.hair,
  "hair up": visibleType.hair,
  "facial mark": visibleType.hair,
  "animal ears": visibleType.hair,
  "cat ears": visibleType.hair,
  "dog ears": visibleType.hair,
  "fox ears": visibleType.hair,
  "animal ear fluff": visibleType.hair,
  fang: visibleType.hair,
  "pointy ears": visibleType.hair,
  forehead: visibleType.face,
  "tress ribbon": visibleType.hair,
  "mole under eye": visibleType.face,
  "asymmetrical hair": visibleType.hair,

  // Breast size
  ...allBreastSizeVisibilities,

  // Body feature
  ...allDistinguishableBodyFeatureVisibilities,
  tail: visibleType.shortTail,
  "cat tail": visibleType.longTail,
  "dog tail": visibleType.longTail,
  "fox tail": visibleType.longTail,
  "demon tail": visibleType.longTail,
  "thick thighs": visibleType.thighs,
  "wide hips": visibleType.hips,
  "mature female": visibleType.all,
  curvy: visibleType.all,
  loli: visibleType.all,
  "cat girl": visibleType.all,
  "dog girl": visibleType.all,
  "fox girl": visibleType.all,
  elf: visibleType.all,
  toned: visibleType.all,
  gyaru: visibleType.all,
  tan: visibleType.all,
  "dark skin": visibleType.all,
  "dark-skinned female": visibleType.all,
  "stomach tattoo": visibleType.navel,

  // Head outfit
  ...allDistinguishableHeadOutfitVisibilities,
  glasses: visibleType.glasses,
  ...allEyewearColorVisibilities,
  "tinted eyewear": visibleType.glasses,
  ...allTintedEyewearColorVisibilities,
  "hair bow": visibleType.hair,
  ...allHairBowColorVisibilities,
  "hair ribbon": visibleType.hair,
  hairband: visibleType.hair,
  ...allHairbandColorVisibilities,
  "heart-shaped eyewear": visibleType.glasses,
  "star-shaped eyewear": visibleType.glasses,
  "teardrop-framed glasses": visibleType.glasses,
  "rectangular eyewear": visibleType.glasses,
  "round eyewear": visibleType.glasses,
  "rimless eyewear": visibleType.glasses,
  "semi-rimless eyewear": visibleType.glasses,
  "over-rim eyewear": visibleType.glasses,
  "under-rim eyewear": visibleType.glasses,
  "coke-bottle glasses": visibleType.glasses,
  "opaque glasses": visibleType.glasses,
  sunglasses: visibleType.glasses,
  "aviator sunglasses": visibleType.glasses,
  goggles: visibleType.glasses,
  monocle: visibleType.glasses,
  eyepatch: visibleType.glasses,
  "diving mask": visibleType.glasses,
  "pince-nez": visibleType.glasses,
  scouter: visibleType.glasses,
  "eyewear on head": visibleType.glasses,
  "eyewear on headwear": visibleType.glasses,
  "eyewear strap": visibleType.glasses,
  "no eyewear": visibleType.glasses,
  bespectacled: visibleType.glasses,
  "hair ornament": visibleType.hair,
  hairpin: visibleType.hair,
  hairclip: visibleType.hair,
  "cross hair ornament": visibleType.hair,
  "x hair ornament": visibleType.hair,
  "snowflake hair ornament": visibleType.hair,
  "bat hair ornament": visibleType.hair,
  "anchor hair ornament": visibleType.hair,
  "bone hair ornament": visibleType.hair,
  "butterfly hair ornament": visibleType.hair,
  "cat hair ornament": visibleType.hair,
  "character hair ornament": visibleType.hair,
  "clover hair ornament": visibleType.hair,
  "coin hair ornament": visibleType.hair,
  "crescent hair ornament": visibleType.hair,
  "cube hair ornament": visibleType.hair,
  "d-pad hair ornament": visibleType.hair,
  "feather hair ornament": visibleType.hair,
  "fish hair ornament": visibleType.hair,
  "food-themed hair ornament": visibleType.hair,
  "frog hair ornament": visibleType.hair,
  "hair beads": visibleType.hair,
  "hair bell": visibleType.hair,
  "hair bobbles": visibleType.hair,
  "hair flower": visibleType.hair,
  "hair scrunchie": visibleType.hair,
  "hair stick": visibleType.hair,
  "heart hair ornament": visibleType.hair,
  kanzashi: visibleType.hair,
  "leaf hair ornament": visibleType.hair,
  "monocle hair ornament": visibleType.hair,
  "musical note hair ornament": visibleType.hair,
  "pom pom hair ornament": visibleType.hair,
  "rabbit hair ornament": visibleType.hair,
  "shark hair ornament": visibleType.hair,
  "skull hair ornament": visibleType.hair,
  "snake hair ornament": visibleType.hair,
  "star hair ornament": visibleType.hair,
  "tassel hair ornament": visibleType.hair,
  crown: visibleType.hair,
  tiara: visibleType.hair,
  diadem: visibleType.hair,
  headdress: visibleType.hair,
  "maid headdress": visibleType.hair,
  veil: visibleType.hair,
  headband: visibleType.hair,
  "bow hairband": visibleType.hair,
  "frilled hairband": visibleType.hair,
  "lace-trimmed hairband": visibleType.hair,
  "lolita hairband": visibleType.hair,
  "striped hairband": visibleType.hair,
  "two-tone hairband": visibleType.hair,
  "gold hairband": visibleType.hair,
  earrings: visibleType.hair,
  "gold earrings": visibleType.hair,
  "flower knot": visibleType.hair,

  // Exposure
  ...allDistinguishableExposureVisibilities,
  collarbone: visibleType.bowtie,
  "bare shoulders": visibleType.shoulder,
  "bare arms": visibleType.shoulder,
  nipples: visibleType.nipples,
  "covered niples": visibleType.nipples,
  midriff: visibleType.navel,
  navel: visibleType.navel,
  "covered navel": visibleType.navel,
  "shoulder blades": visibleType["shoulder blades"],
  "skin tight": visibleType.dress,
  "bare legs": visibleType.thighs,
  cameltoe: visibleType.cameltoe,
  pussy: visibleType.cameltoe,
  ass: visibleType.hips,
  "butt crack": visibleType.hips,
  barefoot: visibleType.foot,
  "no shoes": visibleType.foot,
  "partially unbuttoned": visibleType.bowtie,
  "partially undressed": visibleType.dress,
  nsfw: visibleType.all,
  "shiny skin": visibleType.all,

  // Outfit
  ...allDistinguishableOutfitVisibilities,
  shirt: visibleType.shirt,
  ...allShirtColorVisibilities,
  skirt: visibleType.skirt,
  ...allSkirtColorVisibilities,
  panties: visibleType.panties,
  ...allPantiesColorVisibilities,
  bowtie: visibleType.bowtie,
  ...allBowtieColorVisibilities,
  bikini: visibleType.dress,
  ...allBikiniColorVisibilities,
  "school swimsuit": visibleType.dress,
  ...allOnePieceSwimsuitColorVisibilities,
  jacket: visibleType.shirt,
  ...allJacketColorVisibilities,
  dress: visibleType.dress,
  ...allDressColorVisibilities,
  sweater: visibleType.shirt,
  ...allSweaterColorVisibilities,
  "sweater vest": visibleType.shirt,
  ...allSweaterVestColorVisibilities,
  gloves: visibleType["wrist cuffs"],
  ...allGlovesColorVisibilities,
  thighhighs: visibleType.thighhighs,
  ...allThighhighsColorVisibilities,
  socks: visibleType.foot,
  ...allSocksColorVisibilities,
  collar: visibleType.collar,
  ...allCollarColorVisibilities,
  ...allSleevesColorVisibilities,
  belt: visibleType.skirt,
  ...allBeltColorVisibilities,
  vest: visibleType.shirt,
  ...allVestColorVisibilities,
  ascot: visibleType.bowtie,
  ...allAscotColorVisibilities,
  leotard: visibleType.dress,
  ...allLeotardColorVisibilities,
  neckerchief: visibleType.bowtie,
  ...allNeckerchiefColorVisibilities,
  "sailor collar": visibleType.collar,
  ...allSailorCollarColorVisibilities,
  serafuku: visibleType.shirt,
  ...allSerafukuColorVisibilities,
  camisole: visibleType.shirt,
  ...allCamisoleColorVisibilities,
  shorts: visibleType.skirt,
  ...allShortsColorVisibilities,
  buruma: visibleType.skirt,
  ...allBurumaColorVisibilities,
  necktie: visibleType.bowtie,
  ...allNecktieColorVisibilities,
  hat: visibleType.hat,
  ...allHatColorVisibilities,
  boots: visibleType.foot,
  shoes: visibleType.foot,
  ...allFootwearColorVisibilities,

  "ribbed sweater": visibleType.shirt,
  "striped sweater": visibleType.shirt,
  "plaid sweater": visibleType.shirt,
  "polka dot sweater": visibleType.shirt,
  "argyle sweater": visibleType.shirt,
  "argyle sweater vest": visibleType.shirt,
  "cleavage cutout": visibleType.cleavage,
  "navel cutout": visibleType.navel,
  "neck ribbon": visibleType.bowtie,
  underbust: visibleType.underbust,
  buttons: visibleType.dress,
  jewelry: visibleType.all,
  "frilled bikini": visibleType.dress,
  "print bikini": visibleType.dress,
  "o-ring bikini": visibleType.dress,
  "micro bikini": visibleType.dress,
  "argyle bikini": visibleType.dress,
  "checkered bikini": visibleType.dress,
  "plaid bikini": visibleType.dress,
  "polka dot bikini": visibleType.dress,
  "striped bikini": visibleType.dress,
  "front-tie bikini top": visibleType.bowtie,
  "side-tie bikini bottom": visibleType["side-tie bikini bottom"],
  sarong: visibleType.skirt,
  "o-ring top": visibleType.cleavage,
  "o-ring bottom": visibleType.panties,
  "school uniform": visibleType.dress,
  "sleeveless jacket": visibleType.shirt,
  "military jacket": visibleType.shirt,
  "two-tone dress": visibleType.dress,
  "long sleeves": visibleType.shoulder,
  "wide sleeves": visibleType.shoulder,
  "detached collar": visibleType.collar,
  "detached sleeves": visibleType["wrist cuffs"],
  maid: visibleType.all,
  "maid bikini": visibleType.dress,
  frills: visibleType.all,
  "center frills": visibleType["center frills"],
  apron: visibleType.dress,
  "frilled apron": visibleType.dress,
  "maid apron": visibleType.dress,
  "waist apron": visibleType.skirt,
  "collared shirt": visibleType.shirt,
  "off shoulder": visibleType.shirt,
  "off-shoulder dress": visibleType.dress,
  "off-shoulder sweater": visibleType.shirt,
  "sweater dress": visibleType.dress,
  "office lady": visibleType.all,
  choker: visibleType.collar,
  "ribbon choker": visibleType.collar,
  strap: visibleType.all,
  "fingerless gloves": visibleType["wrist cuffs"],
  "infinite stratos academy school uniform": visibleType.all,
  "lycoris uniform": visibleType.all,
  "pleated dress": visibleType.dress,
  "bikini skirt": visibleType.skirt,
  miniskirt: visibleType.skirt,
  "plaid skirt": visibleType.skirt,
  "pencil skirt": visibleType.skirt,
  "high-low skirt": visibleType.skirt,
  pantyhose: visibleType.thighhighs,
  loafers: visibleType.foot,
  sneakers: visibleType.foot,
  underwear: visibleType.dress,
  "underwear only": visibleType.dress,
  lingerie: visibleType.dress,
  bra: visibleType.bra,
  "crotch seam": visibleType.cameltoe,
  "lace panties": visibleType.panties,
  "tokiwadai school uniform": visibleType.all,
  "short sleeves": visibleType.shoulder,
  "elbow gloves": visibleType["elbow gloves"],
  "pleated skirt": visibleType.skirt,
  "frilled skirt": visibleType.skirt,
  sleeveless: visibleType.shoulder,
  "sleeveless shirt": visibleType.shirt,
  "sleeveless dress": visibleType.dress,
  aiguillette: visibleType.bowtie,
  epaulettes: visibleType.shoulder,
  blazer: visibleType.shirt,
  suit: visibleType.shirt,
  "business suit": visibleType.shirt,
  pumps: visibleType.foot,
  "open clothes": visibleType.shirt, // Visible from back. Assume when all fours.
  "open jacket": visibleType.shirt, // Visible from back. Assume when all fours.
  "open shirt": visibleType.shirt,
  pirate: visibleType.all,
  "pirate hat": visibleType.hat,
  "knee boots": visibleType.foot,
  "thigh boots": visibleType.thighhighs,
  "playboy bunny": visibleType.dress,
  "rabbit ears": visibleType.hair,
  "fake animal ears": visibleType.hair,
  "latex leotard": visibleType.dress,
  "wrist cuffs": visibleType["wrist cuffs"],
  "rabbit tail": visibleType.shortTail,
  "magical girl": visibleType.dress,
  cloak: visibleType.dress,
  "white cloak": visibleType.dress,
  hood: visibleType.hair,
  "hood up": visibleType.hair,
  "hooded cloak": visibleType.dress,
  bodystocking: visibleType.all,
  "black footwear": visibleType.foot,
  "cross-laced footwear": visibleType.foot,
  "panties under pantyhose": visibleType.panties,
  "crop top": visibleType.shirt,
  "crop top overhang": visibleType.cleavage,
  "cropped shirt": visibleType.shirt,
  "naked shirt": visibleType.shirt,
  "dress shirt": visibleType.shirt,
  "no bra": visibleType.bra,
  bottomless: visibleType.skirt,
  "denim shorts": visibleType.skirt,
  "bike shorts": visibleType.skirt,
  denim: visibleType.skirt,
  "gym uniform": visibleType.dress,
  "gym shirt": visibleType.shirt,
  sweat: visibleType.all,
  necklace: visibleType.bowtie,
  "wedding dress": visibleType.dress,
  "nontraditional wedding dress": visibleType.dress,
  bride: visibleType.all,
  "bridal veil": visibleType.hair,
  "bridal garter": visibleType.skirt,
  "bridal gauntlets": visibleType.shoulder,
  "bridal lingerie": visibleType.dress,
  "garter belt": visibleType.skirt,
  "garter straps": visibleType.skirt,
  "revealing clothes": visibleType.all,
  "clothing cutout": visibleType["clothing cutout"],
  "sainan high school uniform": visibleType.dress,
  "thigh strap": visibleType.thighhighs,
  "first high school uniform": visibleType.dress,
  "collared dress": visibleType.dress,
  "pencil dress": visibleType.dress,
  "short necktie": visibleType.bowtie,
  "cropped jacket": visibleType.shirt,
  miko: visibleType.dress,
  "nontraditional miko": visibleType.dress,
  hakama: visibleType.shirt,
  "hakama skirt": visibleType.skirt,
  "hip vent": visibleType["side hip"],
  cheerleader: visibleType.dress,
  "cow print": visibleType.dress,
  "cow print bikini": visibleType.dress,
  "cow print gloves": visibleType["wrist cuffs"],
  "cow print thighhighs": visibleType.thighhighs,
  "print gloves": visibleType["wrist cuffs"],
  "print thighhighs": visibleType.thighhighs,
  "neck bell": visibleType.bowtie,
  "santa costume": visibleType.all,
  "santa hat": visibleType.hat,
  "santa bikini": visibleType.dress,
  "fur collar": visibleType.collar,
  "fur-trimmed bikini": visibleType.dress,
  "fur-trimmed skirt": visibleType.skirt,
  "fur-trimmed headwear": visibleType.hat,
  casual: visibleType.dress,
  "t-shirt": visibleType.shirt,
  "cabbie hat": visibleType.hat,
  "bikini top only": visibleType.shirt,
  "high-waist skirt": visibleType["high-waist skirt"],
  "china dress": visibleType.dress,
  "chinese clothes": visibleType.dress,
  "print dress": visibleType.dress,
  "dragon print": visibleType.dress,
  "floral print": visibleType.dress,
  "cherry blossom print": visibleType.dress,
  "short dress": visibleType.dress,
  "side slit": visibleType["side hip"],
  "pelvic curtain": visibleType.skirt,
  "rei no himo": visibleType.bra,
  "animal collar": visibleType.collar,
  armlet: visibleType.armlet,
  "paw gloves": visibleType["wrist cuffs"],
  "animal hands": visibleType["wrist cuffs"],
  "paw shoes": visibleType.foot,
  "official alternate costume": visibleType.all,
  "fur-trimmed collar": visibleType.collar,
  "center opening": visibleType["center frills"],
  "fur-trimmed gloves": visibleType["elbow gloves"],
  "tight clothes": visibleType.shirt,
  "no pants": visibleType.panties,
} as const satisfies {
  [K in CharacterFeatureTag | OutfitAndExposureTag]: Visibility;
};

export const exportAsCSV = (path: string) => {
  const ws = createWriteStream(path);

  ws.write(
    [`tag`, ...visibilityKeys.map((key) => `"${key}"`)].join(`,`) + `\n`,
  ); // Write header

  const tags = getKeys(tagVisibilities);
  for (const tag of tags) {
    const line = [
      `"${tag}"`,
      visibilityKeys.map((key) => (tagVisibilities[tag][key] ? `"O"` : ``)),
    ].join(`,`);
    ws.write(line + `\n`);
  }

  ws.end();
};
