export const allLoraTokens = [`<lora:nishikigi_chisato_v1:0.75>`] as const;
export type LoraToken = (typeof allLoraTokens)[number];

export const allNameTokens = [
  `aacecilia`,
  `cecilia alcott`,
  `charlotte dunois`,
  `kafuu chino`,
  `yor briar`,
  `nishikigi chisato`,
] as const;
export type NameToken = (typeof allNameTokens)[number];

export const allFrontHeadFeatureTokens = [
  `aqua eyes`,
  `black eyes`,
  `blue eyes`,
  `brown eyes`,
  `green eyes`,
  `grey eyes`,
  `orange eyes`,
  `purple eyes`,
  `pink eyes`,
  `red eyes`,
  `white eyes`,
  `yellow eyes`,
  `heterocromia`,
  `tsurime`,
  `tareme`,
  `thick eyebrows`,
  `eyelashes`,
  `long eyelashes`,
  `thick eyelashes`,
  `glasses`,
  `aqua-framed eyewear`,
  `black-framed eyewear`,
  `blue-framed eyewear`,
  `brown-framed eyewear`,
  `green-framed eyewear`,
  `grey-framed eyewear`,
  `orange-framed eyewear`,
  `pink-framed eyewear`,
  `purple-framed eyewear`,
  `red-framed eyewear`,
  `white-framed eyewear`,
  `yellow-framed eyewear`,
  `tinted eyewear`,
  `blue-tinted eyewear`,
  `green-tinted eyewear`,
  `orange-tinted eyewear`,
  `pink-tinted eyewear`,
  `purple-tinted eyewear`,
  `red-tinted eyewear`,
  `yellow-tinted eyewear`,
  `heart-shaped eyewear`,
  `star-shaped eyewear`,
  `teardrop-framed glasses`,
  `rectangular eyewear`,
  `round eyewear`,
  `rimless eyewear`,
  `semi-rimless eyewear`,
  `over-rim eyewear`,
  `under-rim eyewear`,
  `coke-bottle glasses`,
  `opaque glasses`,
  `sunglasses`,
  `aviator sunglasses`,
  `goggles`,
  `monocle`,
  `eyepatch`,
  `diving mask`,
  `pince-nez`,
  `scouter`,
  `eyewear on head`,
  `eyewear on headwear`,
  `eyewear strap`,
  `no eyewear`,
  `bespectacled`,
  `aqua hair`,
  `black hair`,
  `blonde hair`,
  `blue hair`,
  `light blue hair`,
  `dark blue hair`,
  `brown hair`,
  `light brown hair`,
  `green hair`,
  `dark green hair`,
  `light green hair`,
  `grey hair`,
  `orange hair`,
  `pink hair`,
  `purple hair`,
  `light purple hair`,
  `red hair`,
  `white hair`,
  `gradient hair`,
  `colored inner hair`,
  `short hair`,
  `medium hair`,
  `long hair`,
  `very long hair`,
  `absurdly long hair`,
  `bob cut`,
  `inverted bob`,
  `pixie cut`,
  `undercut`,
  `flipped hair`,
  `dreadlocks`,
  `hime cut`,
  `curly hair`,
  `drill hair`,
  `twin drills`,
  `hair flaps`,
  `messy hair`,
  `pointy hair`,
  `ringlets`,
  `straight hair`,
  `wavy hair`,
  `hair over shoulder`,
  `short hair with long locks`,
  `bow-shaped hair`,
  `braid`,
  `braided bangs`,
  `front braid`,
  `side braid`,
  `frentch braid`,
  `crown braid`,
  `single braid`,
  `multiple braids`,
  `twin braids`,
  `low twin braids`,
  `tri braids`,
  `flower-shaped hair`,
  `hair bun`,
  `braided bun`,
  `single hair bun`,
  `double bun`,
  `cone hair bun`,
  `doughnut hair bun`,
  `heart hair bun`,
  `triple bun`,
  `hair rings`,
  `single hair ring`,
  `half updo`,
  `one side up`,
  `two side up`,
  `low-braided long hair`,
  `low-tied long hair`,
  `mizura`,
  `multi-tied-hair`,
  `ponytail`,
  `folded ponytail`,
  `high ponytail`,
  `low ponytail`,
  `short ponytail`,
  `wide ponytail`,
  `side ponytail`,
  `split ponytail`,
  `topknot`,
  `twintails`,
  `low twintails`,
  `short twintails`,
  `tri tails`,
  `arched bangs`,
  `asymmetrical bangs`,
  `bangs pinned back`,
  `blunt bangs`,
  `crossed bangs`,
  `diagonal bangs`,
  `dyed bangs`,
  `hair over eyes`,
  `hair over one eye`,
  `long bangs`,
  `parted bangs`,
  `curtained bangs`,
  `hair between eyes`,
  `hair intakes`,
  `single hair intake`,
  `blunt ends`,
  `swept bangs`,
  `sidelocks`,
  `asymmetrical sidelocks`,
  `drill sidelocks`,
  `low tied sidelocks`,
  `single sidelock`,
  `ahoge`,
  `heart ahoge`,
  `huge ahoge`,
  `antenna hair`,
  `heart antenna hair`,
  `hair pulled back`,
  `hair slicked back`,
  `alternate hairstyle`,
  `hair down`,
  `hair up`,
  `hair ornament`,
  `hairpin`,
  `hairclip`,
  `cross hair ornament`,
  `x hair ornament`,
  `snowflake hair ornament`,
  `bat hair ornament`,
  `anchor hair ornament`,
  `bone hair ornament`,
  `butterfly hair ornament`,
  `cat hair ornament`,
  `character hair ornament`,
  `clover hair ornament`,
  `coin hair ornament`,
  `crescent hair ornament`,
  `cube hair ornament`,
  `d-pad hair ornament`,
  `feather hair ornament`,
  `fish hair ornament`,
  `food-themed hair ornament`,
  `frog hair ornament`,
  `hair beads`,
  `hair bell`,
  `hair bobbles`,
  `hair flower`,
  `hair scrunchie`,
  `hair stick`,
  `heart hair ornament`,
  `kanzashi`,
  `leaf hair ornament`,
  `monocle hair ornament`,
  `musical note hair ornament`,
  `pom pom hair ornament`,
  `rabbit hair ornament`,
  `shark hair ornament`,
  `skull hair ornament`,
  `snake hair ornament`,
  `star hair ornament`,
  `tassel hair ornament`,
  `crown`,
  `tiara`,
  `diadem`,
  `headdress`,
  `maid headdress`,
  `veil`,
  `headband`,
  `hair bow`,
  `red bow`,
  `pink bow`,
  `orange bow`,
  `brown bow`,
  `yellow bow`,
  `green bow`,
  `aqua bow`,
  `blue bow`,
  `purple bow`,
  `black bow`,
  `grey bow`,
  `white bow`,
  `hair ribbon`,
  `red ribbon`,
  `pink ribbon`,
  `orange ribbon`,
  `brown ribbon`,
  `yellow ribbon`,
  `green ribbon`,
  `aqua ribbon`,
  `blue ribbon`,
  `purple ribbon`,
  `black ribbon`,
  `grey ribbon`,
  `white ribbon`,
  `hairband`,
  `red hairband`,
  `pink hairband`,
  `orange hairband`,
  `brown hairband`,
  `yellow hairband`,
  `green hairband`,
  `aqua hairband`,
  `blue hairband`,
  `purple hairband`,
  `black hairband`,
  `grey hairband`,
  `white hairband`,
  `bow hairband`,
  `frilled hairband`,
  `lace-trimmed hairband`,
  `lolita hairband`,
  `striped hairband`,
  `two-tone hairband`,
  `gold hairband`,
  `facial mark`,
  `animal ears`,
  `cat ears`,
  `dog ears`,
  `fox ears`,
  `animal ear fluff`,
  `fang`,
  `pointy ears`,
  `earrings`,
  `gold earrings`,
] as const;
export type FrontHeadFeatureToken = (typeof allFrontHeadFeatureTokens)[number];

export const allBackHeadFeatureTokens = [
  // WIP: Copy from front head.
] as const;
export type BackHeadFeatureToken = (typeof allBackHeadFeatureTokens)[number];

export const allBreastSizeTokens = [
  `flat chest`,
  `small breasts`,
  `medium breasts`,
  `large breasts`,
  `huge breasts`,
] as const;
export type BreastSizeToken = (typeof allBreastSizeTokens)[number];

export const allLowerBodyFeatureTokens = [
  `cat tail`,
  `dog tail`,
  `fox tail`,
  `thick thighs`,
  `wide hips`,
] as const;
export type LowerBodyFeatureToken = (typeof allLowerBodyFeatureTokens)[number];

export const allWholeBodyFeatureTokens = [
  `mature female`,
  `curvy`,
  `loli`,
  `cat girl`,
  `dog girl`,
  `fox girl`,
  `elf`,
] as const;
export type WholeBodyFeatureToken = (typeof allWholeBodyFeatureTokens)[number];

export type ArmpitsToken = `armpits`;

const anyAngleUpperOutfitTokens = [
  `bare shoulders`,
  `bare arms`,
  `skindentation`, // for breasts
  `bikini`,
  `blue bikini`,
  `frilled bikini`,
  `school uniform`,
  `white jacket`,
  `white dress`,
  `black collar`,
  `white shirt`,
  `long sleeves`,
  `white sleeves`,
  `belt`,
  `white belt`,
  `red belt`,
  `detached collar`,
  `detached sleeves`,
  `maid`,
  `maid headdress`, // TODO: Should be in head?
  `maid bikini`,
  `frills`,
  `apron`,
  `frilled apron`,
  `maid apron`,
  `waist apron`,
  `shirt`,
  `collared shirt`,
  `vest`,
  `green vest`,
  `blue vest`,
  `dress`,
  `red dress`,
  `black dress`,
  `grey dress`,
  `two-tone dress`,
  `off shoulder`,
  `off-shoulder dress`,
  `off-shoulder sweater`,
  `sweater`,
  `red sweater`,
  `sweater dress`,
  `office lady`,
  `choker`,
  `strap`,
  `gloves`,
  `black gloves`,
  `fingerless gloves`,
  `lycoris uniform`,
  `chino work`,
  `aachisato`,
] as const;

export const allFrontUpperOutfitTokens = [
  ...anyAngleUpperOutfitTokens,
  `collarbone`,
  `cleavage`,
  `taut clothes`,
  `midriff`,
  `navel`,
  `covered navel`,
  `nipples`,
  `covered nipples`,
  `cleavage cutout`,
  `neck ribbon`,
  `blue ribbon`,
  `underbust`,
  `bowtie`,
  `blue bowtie`,
  `buttons`,
  `jewelry`,
] as const;
export type FrontUpperOutfitToken = (typeof allFrontUpperOutfitTokens)[number];

export const allSideUpperOutfitTokens = [
  ...anyAngleUpperOutfitTokens,
  `sideboob`,
] as const;
export type SideUpperOutfitToken = (typeof allSideUpperOutfitTokens)[number];

export const allBackUpperOutfitTokens = [
  ...anyAngleUpperOutfitTokens,
  `shoulder blades`,
] as const;
export type BackUpperOutfitToken = (typeof allBackUpperOutfitTokens)[number];

const anyAngleLowerOutfitTokens = [
  `skindentation`, // for thighs
  `bare legs`,
  `pleated dress`,
  `bikini skirt`,
  `skirt`,
  `white skirt`,
  `black skirt`,
  `green skirt`,
  `miniskirt`,
  `pencil skirt`,
  `red trim`,
  `pantyhose`,
  `thighhighs`,
  `black thighhighs`,
] as const;

export const allFrontLowerOutfitTokens = [
  ...anyAngleLowerOutfitTokens,
  `cameltoe`,
  `pussy`,
  `zettai ryouiki`,
  `thigh gap`,
  `ass visible through thighs`,
  `thigh gap`,
] as const;
export type FrontLowerOutfitToken = (typeof allFrontLowerOutfitTokens)[number];

export const allSideLowerOutfitTokens = [
  ...anyAngleLowerOutfitTokens,
  `ass`,
] as const;
export type SideLowerOutfitToken = (typeof allSideLowerOutfitTokens)[number];

export const allBackLowerOutfitTokens = [
  ...anyAngleLowerOutfitTokens,
  `ass`,
  `thigh gap`,
] as const;
export type BackLowerOutfitToken = (typeof allFrontLowerOutfitTokens)[number];

export const allUpskirtOutfitTokens = [
  `panties`,
  `red panties`,
  `blue panties`,
  `pink panties`,
  `crotch seam`,
  `lace panties`,
] as const;
export type UpskirtOutfitToken = (typeof allUpskirtOutfitTokens)[number];

export const allProfileEmotionCandidates = [
  [`blush`, `smile`],
  [`blush`, `light smile`],
  [`blush`, `smile`, `parted lips`],
  [`blush`, `smile`, `:d`, `open mouth`],
  [`blush`, `smile`, `half-closed eyes`],
  [`blush`, `expressionless`],
  [`blush`, `surprised`, `:o`, `open mouth`],
  [`blush`, `nose blush`, `embarrassed`],
  [`blush`, `nose blush`, `nervous`],
  [`blush`, `nose blush`, `flustered`],
  [`blush`, `naughty face`, `smile`, `half-closed eyes`],
  [`blush`, `nose blush`, `scowl`],
] as const;
export type ProfileEmotionCandidate =
  (typeof allProfileEmotionCandidates)[number];

export const allEmotionCandidates = [
  ...allProfileEmotionCandidates,
  [`blush`, `smile`, `one eye closed`, `;)`, `closed mouth`],
  [`blush`, `smile`, `one eye closed`, `;d`, `open mouth`],
] as const;
export type EmotionCandidate = (typeof allEmotionCandidates)[number];

export const allBackgrounds = {
  "from horizontal": [
    [`indoors`],
    [`indoors`, `cafe`],
    [`indoors`, `bed`, `lamp`],
    [`indoors`, `window`],
    [`indoors`, `classroom`],
    [`indoors`, `office`],
    [`indoors`, `night`, `window`],
    [`outdoors`],
    [`outdoors`, `beach`],
    [`outdoors`, `ocean`],
    [`outdoors`, `city`],
    [`outdoors`, `rooftop`, `cityscape`],
    [`outdoors`, `confetti`, `blue sky`],
    [`outdoors`, `mountain`, `rock`],
    [`outdoors`, `forest`],
    [`outdoors`, `garden`],
    [`outdoors`, `night`],
    [`simple background`, `white background`],
    [
      `simple background`,
      `white background`,
      `heart background`,
      `heart`,
      `spoken heart`,
    ],
    [`cave interior`],
  ],
  "from below": [
    [`indoors`],
    [`indoors`, `ceiling`],
    [`indoors`, `ceiling`, `office`],
    [`outdoors`],
    [`outdoors`, `blue sky`],
    [`outdoors`, `sunset`, `orange sky`],
    [`outdoors`, `night`, `night sky`],
    [
      `simple background`,
      `white background`,
      `heart background`,
      `heart`,
      `spoken heart`,
    ],
  ],
  "from above": [
    [`bed sheet`],
    [`indoors`],
    [`indoors`, `wooden floor`],
    [`indoors`, `floor`, `office`],
    [`outdoors`],
    [`outdoors`, `grass`],
    [`outdoors`, `ocean`],
    [`outdoors`, `night`],
    [
      `simple background`,
      `white background`,
      `heart background`,
      `heart`,
      `spoken heart`,
    ],
  ],
  lying: [
    [`bed sheet`],
    [`outdoors`, `grass`],
    [`outdoors`, `ocean`, `partially submerged`],
    [`simple background`, `white background`],
    [`simple background`, `pink background`],
    [`simple background`, `white background`, `heart background`],
    [`simple background`, `pink background`, `heart background`],
    [
      `simple background`,
      `white background`,
      `heart background`,
      `heart`,
      `spoken heart`,
    ],
  ],
} as const;
export type BackgroundDefine = {
  fromHorizontal: (typeof allBackgrounds)["from horizontal"][number][];
  fromBelow: (typeof allBackgrounds)["from below"][number][];
  fromAbove: (typeof allBackgrounds)["from above"][number][];
  lying: (typeof allBackgrounds.lying)[number][];
};

export const BreastSizeOrder: { [k in BreastSizeToken]: number } = {
  "flat chest": 1,
  "small breasts": 2,
  "medium breasts": 3,
  "large breasts": 4,
  "huge breasts": 5,
} as const;
