const allLoraTokens = [
  `<lora:nishikigi_chisato_v1:0.75>`, // https://civitai.com/models/235178/nishikigi-chisato-lycoris-recoil
] as const satisfies readonly string[];
export type LoraToken = (typeof allLoraTokens)[number];

const allNameTokens = [
  `aacecilia`,
  `cecilia alcott`,
  `charlotte dunois`,
  `kafuu chino`,
  `yor briar`,
  `nishikigi chisato`,
] as const satisfies readonly string[];
export type NameToken = (typeof allNameTokens)[number];

const allHeadFeatureTokens = [
  `aqua eyes`,
  `black eyes`,
  `blue eyes`,
  `brown eyes`,
  `green eyes`,
  `grey eyes`,
  `orange eyes`,
  `purple eyes`,
  `pink eyes`,
  `red eyes`,
  `white eyes`,
  `yellow eyes`,
  `heterocromia`,
  `tsurime`,
  `tareme`,
  `thick eyebrows`,
  `eyelashes`,
  `long eyelashes`,
  `thick eyelashes`,
  `glasses`,
  `aqua-framed eyewear`,
  `black-framed eyewear`,
  `blue-framed eyewear`,
  `brown-framed eyewear`,
  `green-framed eyewear`,
  `grey-framed eyewear`,
  `orange-framed eyewear`,
  `pink-framed eyewear`,
  `purple-framed eyewear`,
  `red-framed eyewear`,
  `white-framed eyewear`,
  `yellow-framed eyewear`,
  `tinted eyewear`,
  `blue-tinted eyewear`,
  `green-tinted eyewear`,
  `orange-tinted eyewear`,
  `pink-tinted eyewear`,
  `purple-tinted eyewear`,
  `red-tinted eyewear`,
  `yellow-tinted eyewear`,
  `heart-shaped eyewear`,
  `star-shaped eyewear`,
  `teardrop-framed glasses`,
  `rectangular eyewear`,
  `round eyewear`,
  `rimless eyewear`,
  `semi-rimless eyewear`,
  `over-rim eyewear`,
  `under-rim eyewear`,
  `coke-bottle glasses`,
  `opaque glasses`,
  `sunglasses`,
  `aviator sunglasses`,
  `goggles`,
  `monocle`,
  `eyepatch`,
  `diving mask`,
  `pince-nez`,
  `scouter`,
  `eyewear on head`,
  `eyewear on headwear`,
  `eyewear strap`,
  `no eyewear`,
  `bespectacled`,
  `aqua hair`,
  `black hair`,
  `blonde hair`,
  `blue hair`,
  `light blue hair`,
  `dark blue hair`,
  `brown hair`,
  `light brown hair`,
  `green hair`,
  `dark green hair`,
  `light green hair`,
  `grey hair`,
  `orange hair`,
  `pink hair`,
  `purple hair`,
  `light purple hair`,
  `red hair`,
  `white hair`,
  `gradient hair`,
  `colored inner hair`,
  `short hair`,
  `medium hair`,
  `long hair`,
  `very long hair`,
  `absurdly long hair`,
  `bob cut`,
  `inverted bob`,
  `pixie cut`,
  `undercut`,
  `flipped hair`,
  `dreadlocks`,
  `hime cut`,
  `curly hair`,
  `drill hair`,
  `twin drills`,
  `hair flaps`,
  `messy hair`,
  `pointy hair`,
  `ringlets`,
  `straight hair`,
  `wavy hair`,
  `hair over shoulder`,
  `short hair with long locks`,
  `bow-shaped hair`,
  `braid`,
  `braided bangs`,
  `front braid`,
  `side braid`,
  `frentch braid`,
  `crown braid`,
  `single braid`,
  `multiple braids`,
  `twin braids`,
  `low twin braids`,
  `tri braids`,
  `flower-shaped hair`,
  `hair bun`,
  `braided bun`,
  `single hair bun`,
  `double bun`,
  `cone hair bun`,
  `doughnut hair bun`,
  `heart hair bun`,
  `triple bun`,
  `hair rings`,
  `single hair ring`,
  `half updo`,
  `one side up`,
  `two side up`,
  `low-braided long hair`,
  `low-tied long hair`,
  `mizura`,
  `multi-tied-hair`,
  `ponytail`,
  `folded ponytail`,
  `high ponytail`,
  `low ponytail`,
  `short ponytail`,
  `wide ponytail`,
  `side ponytail`,
  `split ponytail`,
  `topknot`,
  `twintails`,
  `low twintails`,
  `short twintails`,
  `tri tails`,
  `arched bangs`,
  `asymmetrical bangs`,
  `bangs pinned back`,
  `blunt bangs`,
  `crossed bangs`,
  `diagonal bangs`,
  `dyed bangs`,
  `hair over eyes`,
  `hair over one eye`,
  `long bangs`,
  `parted bangs`,
  `curtained bangs`,
  `hair between eyes`,
  `hair intakes`,
  `single hair intake`,
  `blunt ends`,
  `swept bangs`,
  `sidelocks`,
  `asymmetrical sidelocks`,
  `drill sidelocks`,
  `low tied sidelocks`,
  `single sidelock`,
  `ahoge`,
  `heart ahoge`,
  `huge ahoge`,
  `antenna hair`,
  `heart antenna hair`,
  `hair pulled back`,
  `hair slicked back`,
  `alternate hairstyle`,
  `hair down`,
  `hair up`,
  `hair ornament`,
  `hairpin`,
  `hairclip`,
  `cross hair ornament`,
  `x hair ornament`,
  `snowflake hair ornament`,
  `bat hair ornament`,
  `anchor hair ornament`,
  `bone hair ornament`,
  `butterfly hair ornament`,
  `cat hair ornament`,
  `character hair ornament`,
  `clover hair ornament`,
  `coin hair ornament`,
  `crescent hair ornament`,
  `cube hair ornament`,
  `d-pad hair ornament`,
  `feather hair ornament`,
  `fish hair ornament`,
  `food-themed hair ornament`,
  `frog hair ornament`,
  `hair beads`,
  `hair bell`,
  `hair bobbles`,
  `hair flower`,
  `hair scrunchie`,
  `hair stick`,
  `heart hair ornament`,
  `kanzashi`,
  `leaf hair ornament`,
  `monocle hair ornament`,
  `musical note hair ornament`,
  `pom pom hair ornament`,
  `rabbit hair ornament`,
  `shark hair ornament`,
  `skull hair ornament`,
  `snake hair ornament`,
  `star hair ornament`,
  `tassel hair ornament`,
  `crown`,
  `tiara`,
  `diadem`,
  `headdress`,
  `maid headdress`,
  `veil`,
  `headband`,
  `hair bow`,
  `red bow`,
  `pink bow`,
  `orange bow`,
  `brown bow`,
  `yellow bow`,
  `green bow`,
  `aqua bow`,
  `blue bow`,
  `purple bow`,
  `black bow`,
  `grey bow`,
  `white bow`,
  `hair ribbon`,
  `red ribbon`,
  `pink ribbon`,
  `orange ribbon`,
  `brown ribbon`,
  `yellow ribbon`,
  `green ribbon`,
  `aqua ribbon`,
  `blue ribbon`,
  `purple ribbon`,
  `black ribbon`,
  `grey ribbon`,
  `white ribbon`,
  `hairband`,
  `red hairband`,
  `pink hairband`,
  `orange hairband`,
  `brown hairband`,
  `yellow hairband`,
  `green hairband`,
  `aqua hairband`,
  `blue hairband`,
  `purple hairband`,
  `black hairband`,
  `grey hairband`,
  `white hairband`,
  `bow hairband`,
  `frilled hairband`,
  `lace-trimmed hairband`,
  `lolita hairband`,
  `striped hairband`,
  `two-tone hairband`,
  `gold hairband`,
  `facial mark`,
  `animal ears`,
  `cat ears`,
  `dog ears`,
  `fox ears`,
  `animal ear fluff`,
  `fang`,
  `pointy ears`,
  `earrings`,
  `gold earrings`,
] as const satisfies readonly string[];
export type HeadFeatureToken = (typeof allHeadFeatureTokens)[number];

const allBreastSizeTokens = [
  `flat chest`,
  `small breasts`,
  `medium breasts`,
  `large breasts`,
  `huge breasts`,
] as const satisfies readonly string[];
export type BreastSizeToken = (typeof allBreastSizeTokens)[number];

const allBodyFeatureTokens = [
  `cat tail`,
  `dog tail`,
  `fox tail`,
  `thick thighs`,
  `wide hips`,
  `mature female`,
  `curvy`,
  `loli`,
  `cat girl`,
  `dog girl`,
  `fox girl`,
  `elf`,
] as const satisfies readonly string[];
export type BodyFeatureToken = (typeof allBodyFeatureTokens)[number];

const allOutfitAndExposureTokens = [
  // Exposures
  `collarbone`,
  `bare shoulders`,
  `armpits`,
  `bare arms`,
  `cleavage`,
  `sideboob`,
  `backboob`,
  `nipples`,
  `covered niples`,
  `midriff`,
  `navel`,
  `covered navel`,
  `shoulder blades`,
  `taut clothes`,
  `skindentation`,
  `bare legs`,
  `cameltoe`,
  `pussy`,
  `zettai ryouiki`,
  `thigh gap`,
  `ass visible through thighs`,
  `ass`,
  // Outfits
  `cleavage cutout`,
  `neck ribbon`,
  `blue ribbon`,
  `underbust`,
  `bowtie`,
  `blue bowtie`,
  `buttons`,
  `jewelry`,
  `bikini`,
  `blue bikini`,
  `frilled bikini`,
  `school uniform`,
  `white jacket`,
  `white dress`,
  `black collar`,
  `white shirt`,
  `long sleeves`,
  `white sleeves`,
  `belt`,
  `white belt`,
  `red belt`,
  `detached collar`,
  `detached sleeves`,
  `maid`,
  `maid headdress`,
  `maid bikini`,
  `frills`,
  `apron`,
  `frilled apron`,
  `maid apron`,
  `waist apron`,
  `shirt`,
  `collared shirt`,
  `vest`,
  `green vest`,
  `blue vest`,
  `dress`,
  `red dress`,
  `black dress`,
  `grey dress`,
  `two-tone dress`,
  `off shoulder`,
  `off-shoulder dress`,
  `off-shoulder sweater`,
  `sweater`,
  `red sweater`,
  `sweater dress`,
  `office lady`,
  `choker`,
  `strap`,
  `gloves`,
  `black gloves`,
  `fingerless gloves`,
  `lycoris uniform`,
  `pleated dress`,
  `bikini skirt`,
  `skirt`,
  `white skirt`,
  `black skirt`,
  `green skirt`,
  `miniskirt`,
  `pencil skirt`,
  `red trim`,
  `pantyhose`,
  `thighhighs`,
  `black thighhighs`,
  `socks`,
  `white socks`,
  `black socks`,
  `loafers`,
  // Upskirt tokens
  `panties`,
  `red panties`,
  `blue panties`,
  `pink panties`,
  `crotch seam`,
  `lace panties`,
  // Lora specified
  `chino work`,
  `aachisato`,
] as const satisfies readonly string[];
export type OutfitAndExposureToken =
  (typeof allOutfitAndExposureTokens)[number];

const allEmotionTokens = [
  `blush`,
  `nose blush`,
  `smile`,
  `light smile`,
  `parted lips`,
  `:d`,
  `;d`,
  `:)`,
  `;)`,
  `:o`,
  `;o`,
  `open mouth`,
  `closed mouth`,
  `half-closed eyes`,
  `expressionless`,
  `surprised`,
  `embarrassed`,
  `nervous`,
  `flustered`,
  `naughty face`,
  `scowl`,
  `one eye closed`,
] as const satisfies readonly string[];
export type EmotionToken = (typeof allEmotionTokens)[number];

const allBackgroundTokens = [
  `indoors`,
  `cafe`,
  `bed`,
  `lamp`,
  `window`,
  `classroom`,
  `office`,
  `night`,
  `outdoors`,
  `beach`,
  `ocean`,
  `city`,
  `rooftop`,
  `cityscape`,
  `confetti`,
  `blue sky`,
  `mountain`,
  `rock`,
  `forest`,
  `garden`,
  `simple background`,
  `white background`,
  `pink background`,
  `heart background`,
  `heart`,
  `spoken heart`,
  `cave interior`,
  `ceiling`,
  `sunset`,
  `orange sky`,
  `night sky`,
  `grass`,
  `floor`,
  `wooden floor`,
  `partially submerged`,
  `bed sheet`,
] as const satisfies readonly string[];
export type BackgroundToken = (typeof allBackgroundTokens)[number];

export type PersonToken =
  | (typeof allLoraTokens)[number]
  | (typeof allNameTokens)[number]
  | (typeof allHeadFeatureTokens)[number]
  | (typeof allBreastSizeTokens)[number]
  | (typeof allBodyFeatureTokens)[number]
  | (typeof allOutfitAndExposureTokens)[number]
  | (typeof allEmotionTokens)[number];

export type Token = PersonToken | (typeof allBackgroundTokens)[number];

export type Candidate<T> = readonly T[];

export const allProfileEmotionCandidates = [
  [`blush`, `smile`],
  [`blush`, `light smile`],
  [`blush`, `smile`, `parted lips`],
  [`blush`, `smile`, `:d`, `open mouth`],
  [`blush`, `smile`, `half-closed eyes`],
  [`blush`, `expressionless`],
  [`blush`, `surprised`, `:o`, `open mouth`],
  [`blush`, `nose blush`, `embarrassed`],
  [`blush`, `nose blush`, `nervous`],
  [`blush`, `nose blush`, `flustered`],
  [`blush`, `naughty face`, `smile`, `half-closed eyes`],
  [`blush`, `nose blush`, `scowl`],
] as const satisfies readonly Candidate<EmotionToken>[];
export type ProfileEmotionCandidate =
  (typeof allProfileEmotionCandidates)[number];

export const allFrontEmotionCandidates = [
  ...allProfileEmotionCandidates,
  [`blush`, `smile`, `one eye closed`, `;)`, `closed mouth`],
  [`blush`, `smile`, `one eye closed`, `;d`, `open mouth`],
] as const satisfies readonly Candidate<EmotionToken>[];
export type FrontEmotionCandidate = (typeof allFrontEmotionCandidates)[number];

export type EmotionCandidate = ProfileEmotionCandidate | FrontEmotionCandidate;

export type Background = Readonly<{
  fromHorizontal: readonly Candidate<BackgroundToken>[];
  fromBelow: readonly Candidate<BackgroundToken>[];
  fromAbove: readonly Candidate<BackgroundToken>[];
  lying: readonly Candidate<BackgroundToken>[];
  clean: readonly Candidate<BackgroundToken>[]; // For sitting or all fours.
}>;

export const allBackgrounds = {
  fromHorizontal: [
    [`indoors`],
    [`indoors`, `cafe`],
    [`indoors`, `bed`, `lamp`],
    [`indoors`, `window`],
    [`indoors`, `classroom`],
    [`indoors`, `office`],
    [`indoors`, `night`, `window`],
    [`outdoors`],
    [`outdoors`, `beach`],
    [`outdoors`, `ocean`],
    [`outdoors`, `city`],
    [`outdoors`, `rooftop`, `cityscape`],
    [`outdoors`, `confetti`, `blue sky`],
    [`outdoors`, `mountain`, `rock`],
    [`outdoors`, `forest`],
    [`outdoors`, `garden`],
    [`outdoors`, `night`],
    [`simple background`, `white background`],
    [
      `simple background`,
      `white background`,
      `heart background`,
      `heart`,
      `spoken heart`,
    ],
    [`cave interior`],
  ],
  fromBelow: [
    [`indoors`],
    [`indoors`, `ceiling`],
    [`indoors`, `ceiling`, `office`],
    [`outdoors`],
    [`outdoors`, `blue sky`],
    [`outdoors`, `sunset`, `orange sky`],
    [`outdoors`, `night`, `night sky`],
    [
      `simple background`,
      `white background`,
      `heart background`,
      `heart`,
      `spoken heart`,
    ],
  ],
  fromAbove: [
    [`bed sheet`],
    [`indoors`],
    [`indoors`, `wooden floor`],
    [`indoors`, `floor`, `office`],
    [`outdoors`],
    [`outdoors`, `grass`],
    [`outdoors`, `ocean`],
    [`outdoors`, `night`],
    [
      `simple background`,
      `white background`,
      `heart background`,
      `heart`,
      `spoken heart`,
    ],
  ],
  lying: [
    [`bed sheet`],
    [`outdoors`, `grass`],
    [`outdoors`, `ocean`, `partially submerged`],
    [`simple background`, `white background`],
    [`simple background`, `pink background`],
    [`simple background`, `white background`, `heart background`],
    [`simple background`, `pink background`, `heart background`],
    [
      `simple background`,
      `white background`,
      `heart background`,
      `heart`,
      `spoken heart`,
    ],
  ],
  clean: [
    [`bed sheet`],
    [`indoors`, `bed sheet`, `window`],
    [`outdoors`, `grass`],
    [`outdoors`, `grass`, `blue sky`],
    [`outdoors`, `ocean`, `partially submerged`],
    [`simple background`, `white background`],
    [`simple background`, `pink background`],
    [`simple background`, `white background`, `heart background`],
    [`simple background`, `pink background`, `heart background`],
    [
      `simple background`,
      `white background`,
      `heart background`,
      `heart`,
      `spoken heart`,
    ],
  ],
} as const satisfies Background;

export const BreastSizeOrder = {
  "flat chest": 1,
  "small breasts": 2,
  "medium breasts": 3,
  "large breasts": 4,
  "huge breasts": 5,
} as const satisfies { [K in BreastSizeToken]: number };

export type Visible = Readonly<{
  frontHead: boolean;
  sideHead: boolean;
  backHead: boolean;
  frontPortrait: boolean; // For `portrait` .
  sidePortrait: boolean;
  backPortrait: boolean;
  frontMidriff: boolean; // `For `upper body` .
  sideMidriff: boolean;
  backMidriff: boolean;
  frontThigh: boolean; // For `cowboy shot` .
  sideThigh: boolean;
  backThigh: boolean;
  foot: boolean; // For `full body` or `all fours` .
  upskirt: boolean; // For `upskirt` .
}>;

const all = {
  frontHead: true,
  sideHead: true,
  backHead: true,
  frontPortrait: true,
  sidePortrait: true,
  backPortrait: true,
  frontMidriff: true,
  sideMidriff: true,
  backMidriff: true,
  frontThigh: true,
  sideThigh: true,
  backThigh: true,
  foot: true,
  upskirt: true,
} as const satisfies Visible;

const invisible = {
  frontHead: false,
  sideHead: false,
  backHead: false,
  frontPortrait: false,
  sidePortrait: false,
  backPortrait: false,
  frontMidriff: false,
  sideMidriff: false,
  backMidriff: false,
  frontThigh: false,
  sideThigh: false,
  backThigh: false,
  foot: false,
  upskirt: false,
} as const satisfies Visible;

const head = {
  ...invisible,
  frontHead: true,
  sideHead: true,
  backHead: true,
} as const satisfies Visible;

const breastSize = {
  ...invisible,
  frontPortrait: true,
  sidePortrait: true,
  backPortrait: true,
} as const satisfies Visible;

const midriff = {
  ...invisible,
  frontMidriff: true,
  sideMidriff: true,
  backMidriff: true,
} as const satisfies Visible;

const tail = {
  ...invisible,
  frontMidriff: true,
  sideMidriff: true,
  backMidriff: true,
} as const satisfies Visible;

const shoulder = {
  ...invisible,
  frontPortrait: true,
  sidePortrait: true,
  backPortrait: true,
} as const satisfies Visible;

const thigh = {
  ...invisible,
  frontThigh: true,
  sideThigh: true,
  backThigh: true,
} as const satisfies Visible;

const totalOutfit = {
  ...invisible,
  frontPortrait: true,
  sidePortrait: true,
  backPortrait: true,
  frontMidriff: true,
  sideMidriff: true,
  backMidriff: true,
  frontThigh: true,
  sideThigh: true,
  backThigh: true,
} as const satisfies Visible;

const shirt = {
  ...invisible,
  frontPortrait: true,
  sidePortrait: true,
  backPortrait: true,
  frontMidriff: true,
  sideMidriff: true,
  backMidriff: true,
} as const satisfies Visible;

const skirt = {
  ...invisible,
  frontMidriff: true,
  sideMidriff: true,
  backMidriff: true,
  frontThigh: true,
  sideThigh: true,
  backThigh: true,
} as const satisfies Visible;

const collar = {
  ...invisible,
  frontPortrait: true,
  sidePortrait: true,
  backPortrait: true,
} as const satisfies Visible;

const thighhighs = {
  ...invisible,
  frontThigh: true,
  sideThigh: true,
  backThigh: true,
  foot: true,
} as const satisfies Visible;

const pantyhose = {
  ...invisible,
  frontThigh: true,
  sideThigh: true,
  backThigh: true,
  foot: true,
} as const satisfies Visible;

const panty = {
  ...invisible,
  frontMidriff: true,
  sideMidriff: true,
  backMidriff: true,
  frontThigh: true,
  sideThigh: true,
  backThigh: true,
  upskirt: true,
} as const satisfies Visible;

const upskirt = {
  ...invisible,
  upskirt: true,
} as const satisfies Visible;

const foot = {
  ...invisible,
  foot: true,
} as const satisfies Visible;

export const allTokenVisibilities = {
  "<lora:nishikigi_chisato_v1:0.75>": all,
  aacecilia: all,
  "cecilia alcott": all,
  "charlotte dunois": all,
  "kafuu chino": all,
  "yor briar": all,
  "nishikigi chisato": all,
  "aqua eyes": head,
  "black eyes": head,
  "blue eyes": head,
  "brown eyes": head,
  "green eyes": head,
  "grey eyes": head,
  "orange eyes": head,
  "purple eyes": head,
  "pink eyes": head,
  "red eyes": head,
  "white eyes": head,
  "yellow eyes": head,
  heterocromia: head,
  tsurime: head,
  tareme: head,
  "thick eyebrows": head,
  eyelashes: head,
  "long eyelashes": head,
  "thick eyelashes": head,
  glasses: head,
  "aqua-framed eyewear": head,
  "black-framed eyewear": head,
  "blue-framed eyewear": head,
  "brown-framed eyewear": head,
  "green-framed eyewear": head,
  "grey-framed eyewear": head,
  "orange-framed eyewear": head,
  "pink-framed eyewear": head,
  "purple-framed eyewear": head,
  "red-framed eyewear": head,
  "white-framed eyewear": head,
  "yellow-framed eyewear": head,
  "tinted eyewear": head,
  "blue-tinted eyewear": head,
  "green-tinted eyewear": head,
  "orange-tinted eyewear": head,
  "pink-tinted eyewear": head,
  "purple-tinted eyewear": head,
  "red-tinted eyewear": head,
  "yellow-tinted eyewear": head,
  "heart-shaped eyewear": head,
  "star-shaped eyewear": head,
  "teardrop-framed glasses": head,
  "rectangular eyewear": head,
  "round eyewear": head,
  "rimless eyewear": head,
  "semi-rimless eyewear": head,
  "over-rim eyewear": head,
  "under-rim eyewear": head,
  "coke-bottle glasses": head,
  "opaque glasses": head,
  sunglasses: head,
  "aviator sunglasses": head,
  goggles: head,
  monocle: head,
  eyepatch: head,
  "diving mask": head,
  "pince-nez": head,
  scouter: head,
  "eyewear on head": head,
  "eyewear on headwear": head,
  "eyewear strap": head,
  "no eyewear": head,
  bespectacled: head,
  "aqua hair": head,
  "black hair": head,
  "blonde hair": head,
  "blue hair": head,
  "light blue hair": head,
  "dark blue hair": head,
  "brown hair": head,
  "light brown hair": head,
  "green hair": head,
  "dark green hair": head,
  "light green hair": head,
  "grey hair": head,
  "orange hair": head,
  "pink hair": head,
  "purple hair": head,
  "light purple hair": head,
  "red hair": head,
  "white hair": head,
  "gradient hair": head,
  "colored inner hair": head,
  "short hair": head,
  "medium hair": head,
  "long hair": head,
  "very long hair": head,
  "absurdly long hair": head,
  "bob cut": head,
  "inverted bob": head,
  "pixie cut": head,
  undercut: head,
  "flipped hair": head,
  dreadlocks: head,
  "hime cut": head,
  "curly hair": head,
  "drill hair": head,
  "twin drills": head,
  "hair flaps": head,
  "messy hair": head,
  "pointy hair": head,
  ringlets: head,
  "straight hair": head,
  "wavy hair": head,
  "hair over shoulder": head,
  "short hair with long locks": head,
  "bow-shaped hair": head,
  braid: head,
  "braided bangs": head,
  "front braid": head,
  "side braid": head,
  "frentch braid": head,
  "crown braid": head,
  "single braid": head,
  "multiple braids": head,
  "twin braids": head,
  "low twin braids": head,
  "tri braids": head,
  "flower-shaped hair": head,
  "hair bun": head,
  "braided bun": head,
  "single hair bun": head,
  "double bun": head,
  "cone hair bun": head,
  "doughnut hair bun": head,
  "heart hair bun": head,
  "triple bun": head,
  "hair rings": head,
  "single hair ring": head,
  "half updo": head,
  "one side up": head,
  "two side up": head,
  "low-braided long hair": head,
  "low-tied long hair": head,
  mizura: head,
  "multi-tied-hair": head,
  ponytail: head,
  "folded ponytail": head,
  "high ponytail": head,
  "low ponytail": head,
  "short ponytail": head,
  "wide ponytail": head,
  "side ponytail": head,
  "split ponytail": head,
  topknot: head,
  twintails: head,
  "low twintails": head,
  "short twintails": head,
  "tri tails": head,
  "arched bangs": head,
  "asymmetrical bangs": head,
  "bangs pinned back": head,
  "blunt bangs": head,
  "crossed bangs": head,
  "diagonal bangs": head,
  "dyed bangs": head,
  "hair over eyes": head,
  "hair over one eye": head,
  "long bangs": head,
  "parted bangs": head,
  "curtained bangs": head,
  "hair between eyes": head,
  "hair intakes": head,
  "single hair intake": head,
  "blunt ends": head,
  "swept bangs": head,
  sidelocks: head,
  "asymmetrical sidelocks": head,
  "drill sidelocks": head,
  "low tied sidelocks": head,
  "single sidelock": head,
  ahoge: head,
  "heart ahoge": head,
  "huge ahoge": head,
  "antenna hair": head,
  "heart antenna hair": head,
  "hair pulled back": head,
  "hair slicked back": head,
  "alternate hairstyle": head,
  "hair down": head,
  "hair up": head,
  "hair ornament": head,
  hairpin: head,
  hairclip: head,
  "cross hair ornament": head,
  "x hair ornament": head,
  "snowflake hair ornament": head,
  "bat hair ornament": head,
  "anchor hair ornament": head,
  "bone hair ornament": head,
  "butterfly hair ornament": head,
  "cat hair ornament": head,
  "character hair ornament": head,
  "clover hair ornament": head,
  "coin hair ornament": head,
  "crescent hair ornament": head,
  "cube hair ornament": head,
  "d-pad hair ornament": head,
  "feather hair ornament": head,
  "fish hair ornament": head,
  "food-themed hair ornament": head,
  "frog hair ornament": head,
  "hair beads": head,
  "hair bell": head,
  "hair bobbles": head,
  "hair flower": head,
  "hair scrunchie": head,
  "hair stick": head,
  "heart hair ornament": head,
  kanzashi: head,
  "leaf hair ornament": head,
  "monocle hair ornament": head,
  "musical note hair ornament": head,
  "pom pom hair ornament": head,
  "rabbit hair ornament": head,
  "shark hair ornament": head,
  "skull hair ornament": head,
  "snake hair ornament": head,
  "star hair ornament": head,
  "tassel hair ornament": head,
  crown: head,
  tiara: head,
  diadem: head,
  headdress: head,
  "maid headdress": head,
  veil: head,
  headband: head,
  "hair bow": head,
  "red bow": head,
  "pink bow": head,
  "orange bow": head,
  "brown bow": head,
  "yellow bow": head,
  "green bow": head,
  "aqua bow": head,
  "blue bow": head,
  "purple bow": head,
  "black bow": head,
  "grey bow": head,
  "white bow": head,
  "hair ribbon": all,
  "red ribbon": all,
  "pink ribbon": all,
  "orange ribbon": all,
  "brown ribbon": all,
  "yellow ribbon": all,
  "green ribbon": all,
  "aqua ribbon": all,
  "blue ribbon": all,
  "purple ribbon": all,
  "black ribbon": all,
  "grey ribbon": all,
  "white ribbon": all,
  hairband: head,
  "red hairband": head,
  "pink hairband": head,
  "orange hairband": head,
  "brown hairband": head,
  "yellow hairband": head,
  "green hairband": head,
  "aqua hairband": head,
  "blue hairband": head,
  "purple hairband": head,
  "black hairband": head,
  "grey hairband": head,
  "white hairband": head,
  "bow hairband": head,
  "frilled hairband": head,
  "lace-trimmed hairband": head,
  "lolita hairband": head,
  "striped hairband": head,
  "two-tone hairband": head,
  "gold hairband": head,
  "facial mark": head,
  "animal ears": head,
  "cat ears": head,
  "dog ears": head,
  "fox ears": head,
  "animal ear fluff": head,
  fang: head,
  "pointy ears": head,
  earrings: head,
  "gold earrings": head,
  "flat chest": breastSize,
  "small breasts": breastSize,
  "medium breasts": breastSize,
  "large breasts": breastSize,
  "huge breasts": breastSize,
  "cat tail": tail,
  "dog tail": tail,
  "fox tail": tail,
  "thick thighs": thigh,
  "wide hips": tail,
  "mature female": all,
  curvy: all,
  loli: all,
  "cat girl": all,
  "dog girl": all,
  "fox girl": all,
  elf: all,
  collarbone: {
    ...invisible,
    frontPortrait: true,
    sidePortrait: true,
  },
  "bare shoulders": shoulder,
  armpits: shoulder,
  "bare arms": all,
  cleavage: { ...invisible, frontPortrait: true },
  sideboob: { ...invisible, sidePortrait: true },
  backboob: { ...invisible, backPortrait: true },
  nipples: { ...invisible, frontPortrait: true, sidePortrait: true },
  "covered niples": { ...invisible, frontPortrait: true, sidePortrait: true },
  midriff: { ...invisible, frontMidriff: true, sideMidriff: true },
  navel: { ...invisible, frontMidriff: true, sideMidriff: true },
  "covered navel": { ...invisible, frontMidriff: true, sideMidriff: true },
  "shoulder blades": { ...invisible, backPortrait: true },
  "taut clothes": { ...invisible, frontPortrait: true },
  skindentation: { ...invisible, frontPortrait: true, sidePortrait: true },
  "bare legs": thigh,
  cameltoe: {
    ...invisible,
    frontMidriff: true,
    sideMidriff: true,
    upskirt: true,
  },
  pussy: { ...invisible, frontMidriff: true, sideMidriff: true, upskirt: true },
  "zettai ryouiki": all,
  "thigh gap": all,
  "ass visible through thighs": all,
  ass: all,
  "cleavage cutout": { ...invisible, frontPortrait: true, sidePortrait: true },
  "neck ribbon": { ...invisible, frontPortrait: true, sidePortrait: true },
  underbust: midriff,
  bowtie: { ...invisible, frontPortrait: true, sidePortrait: true },
  "blue bowtie": { ...invisible, frontPortrait: true, sidePortrait: true },
  buttons: all,
  jewelry: all,
  bikini: totalOutfit,
  "blue bikini": totalOutfit,
  "frilled bikini": totalOutfit,
  "school uniform": totalOutfit,
  "white jacket": shirt,
  "white dress": totalOutfit,
  "black collar": collar,
  "white shirt": shirt,
  "long sleeves": all,
  "white sleeves": all,
  belt: skirt,
  "white belt": skirt,
  "red belt": skirt,
  "detached collar": collar,
  "detached sleeves": all,
  maid: all,
  "maid bikini": totalOutfit,
  frills: all,
  apron: totalOutfit,
  "frilled apron": totalOutfit,
  "maid apron": totalOutfit,
  "waist apron": skirt,
  shirt: shirt,
  "collared shirt": shirt,
  vest: shirt,
  "green vest": shirt,
  "blue vest": shirt,
  dress: totalOutfit,
  "red dress": totalOutfit,
  "black dress": totalOutfit,
  "grey dress": totalOutfit,
  "two-tone dress": totalOutfit,
  "off shoulder": shirt,
  "off-shoulder dress": totalOutfit,
  "off-shoulder sweater": shirt,
  sweater: shirt,
  "red sweater": shirt,
  "sweater dress": totalOutfit,
  "office lady": all,
  choker: collar,
  strap: all,
  gloves: all,
  "black gloves": all,
  "fingerless gloves": all,
  "lycoris uniform": all,
  "pleated dress": totalOutfit,
  "bikini skirt": skirt,
  skirt: skirt,
  "white skirt": skirt,
  "black skirt": skirt,
  "green skirt": skirt,
  miniskirt: skirt,
  "pencil skirt": skirt,
  "red trim": all,
  pantyhose: pantyhose,
  thighhighs: thighhighs,
  "black thighhighs": thighhighs,
  socks: foot,
  "white socks": foot,
  "black socks": foot,
  loafers: foot,
  panties: panty,
  "red panties": panty,
  "blue panties": panty,
  "pink panties": panty,
  "crotch seam": upskirt,
  "lace panties": panty,
  "chino work": all,
  aachisato: all,
  blush: all,
  "nose blush": all,
  smile: all,
  "light smile": all,
  "parted lips": all,
  ":d": all,
  ";d": all,
  ":)": all,
  ";)": all,
  ":o": all,
  ";o": all,
  "open mouth": all,
  "closed mouth": all,
  "half-closed eyes": all,
  expressionless: all,
  surprised: all,
  embarrassed: all,
  nervous: all,
  flustered: all,
  "naughty face": all,
  scowl: all,
  "one eye closed": all,
} as const satisfies { [K in PersonToken]: Visible };

// Validation
for (const tokens of [
  allLoraTokens,
  allNameTokens,
  allHeadFeatureTokens,
  allBreastSizeTokens,
  allBodyFeatureTokens,
  allOutfitAndExposureTokens,
  allEmotionTokens,
  allBackgroundTokens,
]) {
  for (const token of tokens) {
    if (2 <= tokens.filter((p) => token === p).length) {
      throw new Error(`\`${token}\` is duplicated!!`);
    }
  }
}

// TODO: Validation as token. eg: `hoge (fuga)` is wrong. `hoge \(fuga\)` is correct.
